// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newActionTargetsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "action-targets",
		Short:  "Manage action targets",
		Hidden: true,
	}

	cmd.AddCommand(newActionTargetsCreateCmd(flags))
	cmd.AddCommand(newActionTargetsDeleteCmd(flags))
	cmd.AddCommand(newActionTargetsDescribeCmd(flags))
	cmd.AddCommand(newActionTargetsUpdateCmd(flags))
	return cmd
}
