// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"

	"aws-pp-pp-cli/internal/store"
	"github.com/spf13/cobra"
)

func newAnalyticsCmd(flags *rootFlags) *cobra.Command {
	var resourceType string
	var groupBy string
	var dbPath string
	var limit int

	cmd := &cobra.Command{
		Use:         "analytics",
		Short:       "Run analytics queries on locally synced data",
		Annotations: map[string]string{"mcp:read-only": "true"},
		Long: `Analyze locally synced data with count, group-by, and summary operations.
Data must be synced first with the sync command.`,
		Example: `  # Count records by type
  aws-pp-pp-cli analytics --type messages

  # Group by a field
  aws-pp-pp-cli analytics --type messages --group-by author_id

  # Top 10 most frequent values
  aws-pp-pp-cli analytics --type messages --group-by channel_id --limit 10 --json`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if dbPath == "" {
				dbPath = defaultDBPath("aws-pp-pp-cli")
			}

			db, err := store.OpenWithContext(cmd.Context(), dbPath)
			if err != nil {
				return fmt.Errorf("opening local database: %w\nRun 'aws-pp-pp-cli sync' first.", err)
			}
			defer db.Close()

			if resourceType == "" {
				// Show summary of all resource types
				status, err := db.Status()
				if err != nil {
					return fmt.Errorf("getting status: %w", err)
				}
				if flags.asJSON {
					enc := json.NewEncoder(os.Stdout)
					enc.SetIndent("", "  ")
					return enc.Encode(status)
				}
				fmt.Println("Resource Type\tCount")
				fmt.Println("-------------\t-----")
				for rt, count := range status {
					fmt.Printf("%s\t%d\n", rt, count)
				}
				return nil
			}

			if groupBy != "" {
				return runGroupBy(db, resourceType, groupBy, limit, flags)
			}

			count, err := db.Count(resourceType)
			if err != nil {
				return fmt.Errorf("counting: %w", err)
			}

			if flags.asJSON {
				result := map[string]any{"resource_type": resourceType, "count": count}
				enc := json.NewEncoder(os.Stdout)
				enc.SetIndent("", "  ")
				return enc.Encode(result)
			}

			fmt.Printf("%s: %d records\n", resourceType, count)
			return nil
		},
	}

	cmd.Flags().StringVar(&resourceType, "type", "", "Resource type to analyze")
	cmd.Flags().StringVar(&groupBy, "group-by", "", "Field to group by")
	cmd.Flags().StringVar(&dbPath, "db", "", "Database path")
	cmd.Flags().IntVar(&limit, "limit", 25, "Max groups to show")

	return cmd
}

func runGroupBy(db *store.Store, resourceType, field string, limit int, flags *rootFlags) error {
	items, err := db.List(resourceType, 0)
	if err != nil {
		return err
	}

	counts := make(map[string]int)
	for _, item := range items {
		var obj map[string]any
		if err := json.Unmarshal(item, &obj); err != nil {
			continue
		}
		val := fmt.Sprintf("%v", obj[field])
		counts[val]++
	}

	type kv struct {
		Key   string `json:"value"`
		Count int    `json:"count"`
	}
	var sorted []kv
	for k, v := range counts {
		sorted = append(sorted, kv{k, v})
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Count > sorted[j].Count })
	if limit > 0 && len(sorted) > limit {
		sorted = sorted[:limit]
	}

	if flags.asJSON {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(sorted)
	}

	fmt.Printf("%s\tCount\n", field)
	fmt.Println("---\t-----")
	for _, kv := range sorted {
		fmt.Printf("%s\t%d\n", kv.Key, kv.Count)
	}
	return nil
}
