// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newInsightsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyFiltersAwsAccountId string
	var bodyFiltersCompanyName string
	var bodyFiltersComplianceAssociatedStandardsId string
	var bodyFiltersComplianceSecurityControlId string
	var bodyFiltersComplianceStatus string
	var bodyFiltersConfidence string
	var bodyFiltersCreatedAt string
	var bodyFiltersCriticality string
	var bodyFiltersDescription string
	var bodyFiltersFindingProviderFieldsConfidence string
	var bodyFiltersFindingProviderFieldsCriticality string
	var bodyFiltersFindingProviderFieldsRelatedFindingsId string
	var bodyFiltersFindingProviderFieldsRelatedFindingsProductArn string
	var bodyFiltersFindingProviderFieldsSeverityLabel string
	var bodyFiltersFindingProviderFieldsSeverityOriginal string
	var bodyFiltersFindingProviderFieldsTypes string
	var bodyFiltersFirstObservedAt string
	var bodyFiltersGeneratorId string
	var bodyFiltersId string
	var bodyFiltersKeyword string
	var bodyFiltersLastObservedAt string
	var bodyFiltersMalwareName string
	var bodyFiltersMalwarePath string
	var bodyFiltersMalwareState string
	var bodyFiltersMalwareType string
	var bodyFiltersNetworkDestinationDomain string
	var bodyFiltersNetworkDestinationIpV4 string
	var bodyFiltersNetworkDestinationIpV6 string
	var bodyFiltersNetworkDestinationPort string
	var bodyFiltersNetworkDirection string
	var bodyFiltersNetworkProtocol string
	var bodyFiltersNetworkSourceDomain string
	var bodyFiltersNetworkSourceIpV4 string
	var bodyFiltersNetworkSourceIpV6 string
	var bodyFiltersNetworkSourceMac string
	var bodyFiltersNetworkSourcePort string
	var bodyFiltersNoteText string
	var bodyFiltersNoteUpdatedAt string
	var bodyFiltersNoteUpdatedBy string
	var bodyFiltersProcessLaunchedAt string
	var bodyFiltersProcessName string
	var bodyFiltersProcessParentPid string
	var bodyFiltersProcessPath string
	var bodyFiltersProcessPid string
	var bodyFiltersProcessTerminatedAt string
	var bodyFiltersProductArn string
	var bodyFiltersProductFields string
	var bodyFiltersProductName string
	var bodyFiltersRecommendationText string
	var bodyFiltersRecordState string
	var bodyFiltersRegion string
	var bodyFiltersRelatedFindingsId string
	var bodyFiltersRelatedFindingsProductArn string
	var bodyFiltersResourceAwsEc2InstanceIamInstanceProfileArn string
	var bodyFiltersResourceAwsEc2InstanceImageId string
	var bodyFiltersResourceAwsEc2InstanceIpV4Addresses string
	var bodyFiltersResourceAwsEc2InstanceIpV6Addresses string
	var bodyFiltersResourceAwsEc2InstanceKeyName string
	var bodyFiltersResourceAwsEc2InstanceLaunchedAt string
	var bodyFiltersResourceAwsEc2InstanceSubnetId string
	var bodyFiltersResourceAwsEc2InstanceType string
	var bodyFiltersResourceAwsEc2InstanceVpcId string
	var bodyFiltersResourceAwsIamAccessKeyCreatedAt string
	var bodyFiltersResourceAwsIamAccessKeyPrincipalName string
	var bodyFiltersResourceAwsIamAccessKeyStatus string
	var bodyFiltersResourceAwsIamAccessKeyUserName string
	var bodyFiltersResourceAwsIamUserUserName string
	var bodyFiltersResourceAwsS3BucketOwnerId string
	var bodyFiltersResourceAwsS3BucketOwnerName string
	var bodyFiltersResourceContainerImageId string
	var bodyFiltersResourceContainerImageName string
	var bodyFiltersResourceContainerLaunchedAt string
	var bodyFiltersResourceContainerName string
	var bodyFiltersResourceDetailsOther string
	var bodyFiltersResourceId string
	var bodyFiltersResourcePartition string
	var bodyFiltersResourceRegion string
	var bodyFiltersResourceTags string
	var bodyFiltersResourceType string
	var bodyFiltersSample string
	var bodyFiltersSeverityLabel string
	var bodyFiltersSeverityNormalized string
	var bodyFiltersSeverityProduct string
	var bodyFiltersSourceUrl string
	var bodyFiltersThreatIntelIndicatorCategory string
	var bodyFiltersThreatIntelIndicatorLastObservedAt string
	var bodyFiltersThreatIntelIndicatorSource string
	var bodyFiltersThreatIntelIndicatorSourceUrl string
	var bodyFiltersThreatIntelIndicatorType string
	var bodyFiltersThreatIntelIndicatorValue string
	var bodyFiltersTitle string
	var bodyFiltersType string
	var bodyFiltersUpdatedAt string
	var bodyFiltersUserDefinedFields string
	var bodyFiltersVerificationState string
	var bodyFiltersWorkflowState string
	var bodyFiltersWorkflowStatus string
	var bodyGroupByAttribute string
	var bodyName string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "<p>Creates a custom insight in Security Hub. An insight is a consolidation of findings that relate to a security...",
		Example:     "  aws-pp-pp-cli insights create --group-by-attribute example-value",
		Annotations: map[string]string{"pp:endpoint": "insights.create", "pp:method": "POST", "pp:path": "http://securityhub.us-east-1.amazonaws.com/insights"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("group-by-attribute") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "group-by-attribute")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://securityhub.us-east-1.amazonaws.com/insights"
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedFilters := map[string]any{}
					if bodyFiltersAwsAccountId != "" {
						var parsedFiltersAwsAccountId any
						if err := json.Unmarshal([]byte(bodyFiltersAwsAccountId), &parsedFiltersAwsAccountId); err != nil {
							return fmt.Errorf("parsing --filters-aws-account-id JSON: %w", err)
						}
						nestedFilters["AwsAccountId"] = parsedFiltersAwsAccountId
					}
					if bodyFiltersCompanyName != "" {
						var parsedFiltersCompanyName any
						if err := json.Unmarshal([]byte(bodyFiltersCompanyName), &parsedFiltersCompanyName); err != nil {
							return fmt.Errorf("parsing --filters-company-name JSON: %w", err)
						}
						nestedFilters["CompanyName"] = parsedFiltersCompanyName
					}
					if bodyFiltersComplianceAssociatedStandardsId != "" {
						var parsedFiltersComplianceAssociatedStandardsId any
						if err := json.Unmarshal([]byte(bodyFiltersComplianceAssociatedStandardsId), &parsedFiltersComplianceAssociatedStandardsId); err != nil {
							return fmt.Errorf("parsing --filters-compliance-associated-standards-id JSON: %w", err)
						}
						nestedFilters["ComplianceAssociatedStandardsId"] = parsedFiltersComplianceAssociatedStandardsId
					}
					if bodyFiltersComplianceSecurityControlId != "" {
						var parsedFiltersComplianceSecurityControlId any
						if err := json.Unmarshal([]byte(bodyFiltersComplianceSecurityControlId), &parsedFiltersComplianceSecurityControlId); err != nil {
							return fmt.Errorf("parsing --filters-compliance-security-control-id JSON: %w", err)
						}
						nestedFilters["ComplianceSecurityControlId"] = parsedFiltersComplianceSecurityControlId
					}
					if bodyFiltersComplianceStatus != "" {
						var parsedFiltersComplianceStatus any
						if err := json.Unmarshal([]byte(bodyFiltersComplianceStatus), &parsedFiltersComplianceStatus); err != nil {
							return fmt.Errorf("parsing --filters-compliance-status JSON: %w", err)
						}
						nestedFilters["ComplianceStatus"] = parsedFiltersComplianceStatus
					}
					if bodyFiltersConfidence != "" {
						var parsedFiltersConfidence any
						if err := json.Unmarshal([]byte(bodyFiltersConfidence), &parsedFiltersConfidence); err != nil {
							return fmt.Errorf("parsing --filters-confidence JSON: %w", err)
						}
						nestedFilters["Confidence"] = parsedFiltersConfidence
					}
					if bodyFiltersCreatedAt != "" {
						var parsedFiltersCreatedAt any
						if err := json.Unmarshal([]byte(bodyFiltersCreatedAt), &parsedFiltersCreatedAt); err != nil {
							return fmt.Errorf("parsing --filters-created-at JSON: %w", err)
						}
						nestedFilters["CreatedAt"] = parsedFiltersCreatedAt
					}
					if bodyFiltersCriticality != "" {
						var parsedFiltersCriticality any
						if err := json.Unmarshal([]byte(bodyFiltersCriticality), &parsedFiltersCriticality); err != nil {
							return fmt.Errorf("parsing --filters-criticality JSON: %w", err)
						}
						nestedFilters["Criticality"] = parsedFiltersCriticality
					}
					if bodyFiltersDescription != "" {
						var parsedFiltersDescription any
						if err := json.Unmarshal([]byte(bodyFiltersDescription), &parsedFiltersDescription); err != nil {
							return fmt.Errorf("parsing --filters-description JSON: %w", err)
						}
						nestedFilters["Description"] = parsedFiltersDescription
					}
					if bodyFiltersFindingProviderFieldsConfidence != "" {
						var parsedFiltersFindingProviderFieldsConfidence any
						if err := json.Unmarshal([]byte(bodyFiltersFindingProviderFieldsConfidence), &parsedFiltersFindingProviderFieldsConfidence); err != nil {
							return fmt.Errorf("parsing --filters-finding-provider-fields-confidence JSON: %w", err)
						}
						nestedFilters["FindingProviderFieldsConfidence"] = parsedFiltersFindingProviderFieldsConfidence
					}
					if bodyFiltersFindingProviderFieldsCriticality != "" {
						var parsedFiltersFindingProviderFieldsCriticality any
						if err := json.Unmarshal([]byte(bodyFiltersFindingProviderFieldsCriticality), &parsedFiltersFindingProviderFieldsCriticality); err != nil {
							return fmt.Errorf("parsing --filters-finding-provider-fields-criticality JSON: %w", err)
						}
						nestedFilters["FindingProviderFieldsCriticality"] = parsedFiltersFindingProviderFieldsCriticality
					}
					if bodyFiltersFindingProviderFieldsRelatedFindingsId != "" {
						var parsedFiltersFindingProviderFieldsRelatedFindingsId any
						if err := json.Unmarshal([]byte(bodyFiltersFindingProviderFieldsRelatedFindingsId), &parsedFiltersFindingProviderFieldsRelatedFindingsId); err != nil {
							return fmt.Errorf("parsing --filters-finding-provider-fields-related-findings-id JSON: %w", err)
						}
						nestedFilters["FindingProviderFieldsRelatedFindingsId"] = parsedFiltersFindingProviderFieldsRelatedFindingsId
					}
					if bodyFiltersFindingProviderFieldsRelatedFindingsProductArn != "" {
						var parsedFiltersFindingProviderFieldsRelatedFindingsProductArn any
						if err := json.Unmarshal([]byte(bodyFiltersFindingProviderFieldsRelatedFindingsProductArn), &parsedFiltersFindingProviderFieldsRelatedFindingsProductArn); err != nil {
							return fmt.Errorf("parsing --filters-finding-provider-fields-related-findings-product-arn JSON: %w", err)
						}
						nestedFilters["FindingProviderFieldsRelatedFindingsProductArn"] = parsedFiltersFindingProviderFieldsRelatedFindingsProductArn
					}
					if bodyFiltersFindingProviderFieldsSeverityLabel != "" {
						var parsedFiltersFindingProviderFieldsSeverityLabel any
						if err := json.Unmarshal([]byte(bodyFiltersFindingProviderFieldsSeverityLabel), &parsedFiltersFindingProviderFieldsSeverityLabel); err != nil {
							return fmt.Errorf("parsing --filters-finding-provider-fields-severity-label JSON: %w", err)
						}
						nestedFilters["FindingProviderFieldsSeverityLabel"] = parsedFiltersFindingProviderFieldsSeverityLabel
					}
					if bodyFiltersFindingProviderFieldsSeverityOriginal != "" {
						var parsedFiltersFindingProviderFieldsSeverityOriginal any
						if err := json.Unmarshal([]byte(bodyFiltersFindingProviderFieldsSeverityOriginal), &parsedFiltersFindingProviderFieldsSeverityOriginal); err != nil {
							return fmt.Errorf("parsing --filters-finding-provider-fields-severity-original JSON: %w", err)
						}
						nestedFilters["FindingProviderFieldsSeverityOriginal"] = parsedFiltersFindingProviderFieldsSeverityOriginal
					}
					if bodyFiltersFindingProviderFieldsTypes != "" {
						var parsedFiltersFindingProviderFieldsTypes any
						if err := json.Unmarshal([]byte(bodyFiltersFindingProviderFieldsTypes), &parsedFiltersFindingProviderFieldsTypes); err != nil {
							return fmt.Errorf("parsing --filters-finding-provider-fields-types JSON: %w", err)
						}
						nestedFilters["FindingProviderFieldsTypes"] = parsedFiltersFindingProviderFieldsTypes
					}
					if bodyFiltersFirstObservedAt != "" {
						var parsedFiltersFirstObservedAt any
						if err := json.Unmarshal([]byte(bodyFiltersFirstObservedAt), &parsedFiltersFirstObservedAt); err != nil {
							return fmt.Errorf("parsing --filters-first-observed-at JSON: %w", err)
						}
						nestedFilters["FirstObservedAt"] = parsedFiltersFirstObservedAt
					}
					if bodyFiltersGeneratorId != "" {
						var parsedFiltersGeneratorId any
						if err := json.Unmarshal([]byte(bodyFiltersGeneratorId), &parsedFiltersGeneratorId); err != nil {
							return fmt.Errorf("parsing --filters-generator-id JSON: %w", err)
						}
						nestedFilters["GeneratorId"] = parsedFiltersGeneratorId
					}
					if bodyFiltersId != "" {
						var parsedFiltersId any
						if err := json.Unmarshal([]byte(bodyFiltersId), &parsedFiltersId); err != nil {
							return fmt.Errorf("parsing --filters-id JSON: %w", err)
						}
						nestedFilters["Id"] = parsedFiltersId
					}
					if bodyFiltersKeyword != "" {
						var parsedFiltersKeyword any
						if err := json.Unmarshal([]byte(bodyFiltersKeyword), &parsedFiltersKeyword); err != nil {
							return fmt.Errorf("parsing --filters-keyword JSON: %w", err)
						}
						nestedFilters["Keyword"] = parsedFiltersKeyword
					}
					if bodyFiltersLastObservedAt != "" {
						var parsedFiltersLastObservedAt any
						if err := json.Unmarshal([]byte(bodyFiltersLastObservedAt), &parsedFiltersLastObservedAt); err != nil {
							return fmt.Errorf("parsing --filters-last-observed-at JSON: %w", err)
						}
						nestedFilters["LastObservedAt"] = parsedFiltersLastObservedAt
					}
					if bodyFiltersMalwareName != "" {
						var parsedFiltersMalwareName any
						if err := json.Unmarshal([]byte(bodyFiltersMalwareName), &parsedFiltersMalwareName); err != nil {
							return fmt.Errorf("parsing --filters-malware-name JSON: %w", err)
						}
						nestedFilters["MalwareName"] = parsedFiltersMalwareName
					}
					if bodyFiltersMalwarePath != "" {
						var parsedFiltersMalwarePath any
						if err := json.Unmarshal([]byte(bodyFiltersMalwarePath), &parsedFiltersMalwarePath); err != nil {
							return fmt.Errorf("parsing --filters-malware-path JSON: %w", err)
						}
						nestedFilters["MalwarePath"] = parsedFiltersMalwarePath
					}
					if bodyFiltersMalwareState != "" {
						var parsedFiltersMalwareState any
						if err := json.Unmarshal([]byte(bodyFiltersMalwareState), &parsedFiltersMalwareState); err != nil {
							return fmt.Errorf("parsing --filters-malware-state JSON: %w", err)
						}
						nestedFilters["MalwareState"] = parsedFiltersMalwareState
					}
					if bodyFiltersMalwareType != "" {
						var parsedFiltersMalwareType any
						if err := json.Unmarshal([]byte(bodyFiltersMalwareType), &parsedFiltersMalwareType); err != nil {
							return fmt.Errorf("parsing --filters-malware-type JSON: %w", err)
						}
						nestedFilters["MalwareType"] = parsedFiltersMalwareType
					}
					if bodyFiltersNetworkDestinationDomain != "" {
						var parsedFiltersNetworkDestinationDomain any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkDestinationDomain), &parsedFiltersNetworkDestinationDomain); err != nil {
							return fmt.Errorf("parsing --filters-network-destination-domain JSON: %w", err)
						}
						nestedFilters["NetworkDestinationDomain"] = parsedFiltersNetworkDestinationDomain
					}
					if bodyFiltersNetworkDestinationIpV4 != "" {
						var parsedFiltersNetworkDestinationIpV4 any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkDestinationIpV4), &parsedFiltersNetworkDestinationIpV4); err != nil {
							return fmt.Errorf("parsing --filters-network-destination-ip-v4 JSON: %w", err)
						}
						nestedFilters["NetworkDestinationIpV4"] = parsedFiltersNetworkDestinationIpV4
					}
					if bodyFiltersNetworkDestinationIpV6 != "" {
						var parsedFiltersNetworkDestinationIpV6 any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkDestinationIpV6), &parsedFiltersNetworkDestinationIpV6); err != nil {
							return fmt.Errorf("parsing --filters-network-destination-ip-v6 JSON: %w", err)
						}
						nestedFilters["NetworkDestinationIpV6"] = parsedFiltersNetworkDestinationIpV6
					}
					if bodyFiltersNetworkDestinationPort != "" {
						var parsedFiltersNetworkDestinationPort any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkDestinationPort), &parsedFiltersNetworkDestinationPort); err != nil {
							return fmt.Errorf("parsing --filters-network-destination-port JSON: %w", err)
						}
						nestedFilters["NetworkDestinationPort"] = parsedFiltersNetworkDestinationPort
					}
					if bodyFiltersNetworkDirection != "" {
						var parsedFiltersNetworkDirection any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkDirection), &parsedFiltersNetworkDirection); err != nil {
							return fmt.Errorf("parsing --filters-network-direction JSON: %w", err)
						}
						nestedFilters["NetworkDirection"] = parsedFiltersNetworkDirection
					}
					if bodyFiltersNetworkProtocol != "" {
						var parsedFiltersNetworkProtocol any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkProtocol), &parsedFiltersNetworkProtocol); err != nil {
							return fmt.Errorf("parsing --filters-network-protocol JSON: %w", err)
						}
						nestedFilters["NetworkProtocol"] = parsedFiltersNetworkProtocol
					}
					if bodyFiltersNetworkSourceDomain != "" {
						var parsedFiltersNetworkSourceDomain any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkSourceDomain), &parsedFiltersNetworkSourceDomain); err != nil {
							return fmt.Errorf("parsing --filters-network-source-domain JSON: %w", err)
						}
						nestedFilters["NetworkSourceDomain"] = parsedFiltersNetworkSourceDomain
					}
					if bodyFiltersNetworkSourceIpV4 != "" {
						var parsedFiltersNetworkSourceIpV4 any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkSourceIpV4), &parsedFiltersNetworkSourceIpV4); err != nil {
							return fmt.Errorf("parsing --filters-network-source-ip-v4 JSON: %w", err)
						}
						nestedFilters["NetworkSourceIpV4"] = parsedFiltersNetworkSourceIpV4
					}
					if bodyFiltersNetworkSourceIpV6 != "" {
						var parsedFiltersNetworkSourceIpV6 any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkSourceIpV6), &parsedFiltersNetworkSourceIpV6); err != nil {
							return fmt.Errorf("parsing --filters-network-source-ip-v6 JSON: %w", err)
						}
						nestedFilters["NetworkSourceIpV6"] = parsedFiltersNetworkSourceIpV6
					}
					if bodyFiltersNetworkSourceMac != "" {
						var parsedFiltersNetworkSourceMac any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkSourceMac), &parsedFiltersNetworkSourceMac); err != nil {
							return fmt.Errorf("parsing --filters-network-source-mac JSON: %w", err)
						}
						nestedFilters["NetworkSourceMac"] = parsedFiltersNetworkSourceMac
					}
					if bodyFiltersNetworkSourcePort != "" {
						var parsedFiltersNetworkSourcePort any
						if err := json.Unmarshal([]byte(bodyFiltersNetworkSourcePort), &parsedFiltersNetworkSourcePort); err != nil {
							return fmt.Errorf("parsing --filters-network-source-port JSON: %w", err)
						}
						nestedFilters["NetworkSourcePort"] = parsedFiltersNetworkSourcePort
					}
					if bodyFiltersNoteText != "" {
						var parsedFiltersNoteText any
						if err := json.Unmarshal([]byte(bodyFiltersNoteText), &parsedFiltersNoteText); err != nil {
							return fmt.Errorf("parsing --filters-note-text JSON: %w", err)
						}
						nestedFilters["NoteText"] = parsedFiltersNoteText
					}
					if bodyFiltersNoteUpdatedAt != "" {
						var parsedFiltersNoteUpdatedAt any
						if err := json.Unmarshal([]byte(bodyFiltersNoteUpdatedAt), &parsedFiltersNoteUpdatedAt); err != nil {
							return fmt.Errorf("parsing --filters-note-updated-at JSON: %w", err)
						}
						nestedFilters["NoteUpdatedAt"] = parsedFiltersNoteUpdatedAt
					}
					if bodyFiltersNoteUpdatedBy != "" {
						var parsedFiltersNoteUpdatedBy any
						if err := json.Unmarshal([]byte(bodyFiltersNoteUpdatedBy), &parsedFiltersNoteUpdatedBy); err != nil {
							return fmt.Errorf("parsing --filters-note-updated-by JSON: %w", err)
						}
						nestedFilters["NoteUpdatedBy"] = parsedFiltersNoteUpdatedBy
					}
					if bodyFiltersProcessLaunchedAt != "" {
						var parsedFiltersProcessLaunchedAt any
						if err := json.Unmarshal([]byte(bodyFiltersProcessLaunchedAt), &parsedFiltersProcessLaunchedAt); err != nil {
							return fmt.Errorf("parsing --filters-process-launched-at JSON: %w", err)
						}
						nestedFilters["ProcessLaunchedAt"] = parsedFiltersProcessLaunchedAt
					}
					if bodyFiltersProcessName != "" {
						var parsedFiltersProcessName any
						if err := json.Unmarshal([]byte(bodyFiltersProcessName), &parsedFiltersProcessName); err != nil {
							return fmt.Errorf("parsing --filters-process-name JSON: %w", err)
						}
						nestedFilters["ProcessName"] = parsedFiltersProcessName
					}
					if bodyFiltersProcessParentPid != "" {
						var parsedFiltersProcessParentPid any
						if err := json.Unmarshal([]byte(bodyFiltersProcessParentPid), &parsedFiltersProcessParentPid); err != nil {
							return fmt.Errorf("parsing --filters-process-parent-pid JSON: %w", err)
						}
						nestedFilters["ProcessParentPid"] = parsedFiltersProcessParentPid
					}
					if bodyFiltersProcessPath != "" {
						var parsedFiltersProcessPath any
						if err := json.Unmarshal([]byte(bodyFiltersProcessPath), &parsedFiltersProcessPath); err != nil {
							return fmt.Errorf("parsing --filters-process-path JSON: %w", err)
						}
						nestedFilters["ProcessPath"] = parsedFiltersProcessPath
					}
					if bodyFiltersProcessPid != "" {
						var parsedFiltersProcessPid any
						if err := json.Unmarshal([]byte(bodyFiltersProcessPid), &parsedFiltersProcessPid); err != nil {
							return fmt.Errorf("parsing --filters-process-pid JSON: %w", err)
						}
						nestedFilters["ProcessPid"] = parsedFiltersProcessPid
					}
					if bodyFiltersProcessTerminatedAt != "" {
						var parsedFiltersProcessTerminatedAt any
						if err := json.Unmarshal([]byte(bodyFiltersProcessTerminatedAt), &parsedFiltersProcessTerminatedAt); err != nil {
							return fmt.Errorf("parsing --filters-process-terminated-at JSON: %w", err)
						}
						nestedFilters["ProcessTerminatedAt"] = parsedFiltersProcessTerminatedAt
					}
					if bodyFiltersProductArn != "" {
						var parsedFiltersProductArn any
						if err := json.Unmarshal([]byte(bodyFiltersProductArn), &parsedFiltersProductArn); err != nil {
							return fmt.Errorf("parsing --filters-product-arn JSON: %w", err)
						}
						nestedFilters["ProductArn"] = parsedFiltersProductArn
					}
					if bodyFiltersProductFields != "" {
						var parsedFiltersProductFields any
						if err := json.Unmarshal([]byte(bodyFiltersProductFields), &parsedFiltersProductFields); err != nil {
							return fmt.Errorf("parsing --filters-product-fields JSON: %w", err)
						}
						nestedFilters["ProductFields"] = parsedFiltersProductFields
					}
					if bodyFiltersProductName != "" {
						var parsedFiltersProductName any
						if err := json.Unmarshal([]byte(bodyFiltersProductName), &parsedFiltersProductName); err != nil {
							return fmt.Errorf("parsing --filters-product-name JSON: %w", err)
						}
						nestedFilters["ProductName"] = parsedFiltersProductName
					}
					if bodyFiltersRecommendationText != "" {
						var parsedFiltersRecommendationText any
						if err := json.Unmarshal([]byte(bodyFiltersRecommendationText), &parsedFiltersRecommendationText); err != nil {
							return fmt.Errorf("parsing --filters-recommendation-text JSON: %w", err)
						}
						nestedFilters["RecommendationText"] = parsedFiltersRecommendationText
					}
					if bodyFiltersRecordState != "" {
						var parsedFiltersRecordState any
						if err := json.Unmarshal([]byte(bodyFiltersRecordState), &parsedFiltersRecordState); err != nil {
							return fmt.Errorf("parsing --filters-record-state JSON: %w", err)
						}
						nestedFilters["RecordState"] = parsedFiltersRecordState
					}
					if bodyFiltersRegion != "" {
						var parsedFiltersRegion any
						if err := json.Unmarshal([]byte(bodyFiltersRegion), &parsedFiltersRegion); err != nil {
							return fmt.Errorf("parsing --filters-region JSON: %w", err)
						}
						nestedFilters["Region"] = parsedFiltersRegion
					}
					if bodyFiltersRelatedFindingsId != "" {
						var parsedFiltersRelatedFindingsId any
						if err := json.Unmarshal([]byte(bodyFiltersRelatedFindingsId), &parsedFiltersRelatedFindingsId); err != nil {
							return fmt.Errorf("parsing --filters-related-findings-id JSON: %w", err)
						}
						nestedFilters["RelatedFindingsId"] = parsedFiltersRelatedFindingsId
					}
					if bodyFiltersRelatedFindingsProductArn != "" {
						var parsedFiltersRelatedFindingsProductArn any
						if err := json.Unmarshal([]byte(bodyFiltersRelatedFindingsProductArn), &parsedFiltersRelatedFindingsProductArn); err != nil {
							return fmt.Errorf("parsing --filters-related-findings-product-arn JSON: %w", err)
						}
						nestedFilters["RelatedFindingsProductArn"] = parsedFiltersRelatedFindingsProductArn
					}
					if bodyFiltersResourceAwsEc2InstanceIamInstanceProfileArn != "" {
						var parsedFiltersResourceAwsEc2InstanceIamInstanceProfileArn any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsEc2InstanceIamInstanceProfileArn), &parsedFiltersResourceAwsEc2InstanceIamInstanceProfileArn); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-ec2-instance-iam-instance-profile-arn JSON: %w", err)
						}
						nestedFilters["ResourceAwsEc2InstanceIamInstanceProfileArn"] = parsedFiltersResourceAwsEc2InstanceIamInstanceProfileArn
					}
					if bodyFiltersResourceAwsEc2InstanceImageId != "" {
						var parsedFiltersResourceAwsEc2InstanceImageId any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsEc2InstanceImageId), &parsedFiltersResourceAwsEc2InstanceImageId); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-ec2-instance-image-id JSON: %w", err)
						}
						nestedFilters["ResourceAwsEc2InstanceImageId"] = parsedFiltersResourceAwsEc2InstanceImageId
					}
					if bodyFiltersResourceAwsEc2InstanceIpV4Addresses != "" {
						var parsedFiltersResourceAwsEc2InstanceIpV4Addresses any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsEc2InstanceIpV4Addresses), &parsedFiltersResourceAwsEc2InstanceIpV4Addresses); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-ec2-instance-ip-v4-addresses JSON: %w", err)
						}
						nestedFilters["ResourceAwsEc2InstanceIpV4Addresses"] = parsedFiltersResourceAwsEc2InstanceIpV4Addresses
					}
					if bodyFiltersResourceAwsEc2InstanceIpV6Addresses != "" {
						var parsedFiltersResourceAwsEc2InstanceIpV6Addresses any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsEc2InstanceIpV6Addresses), &parsedFiltersResourceAwsEc2InstanceIpV6Addresses); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-ec2-instance-ip-v6-addresses JSON: %w", err)
						}
						nestedFilters["ResourceAwsEc2InstanceIpV6Addresses"] = parsedFiltersResourceAwsEc2InstanceIpV6Addresses
					}
					if bodyFiltersResourceAwsEc2InstanceKeyName != "" {
						var parsedFiltersResourceAwsEc2InstanceKeyName any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsEc2InstanceKeyName), &parsedFiltersResourceAwsEc2InstanceKeyName); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-ec2-instance-key-name JSON: %w", err)
						}
						nestedFilters["ResourceAwsEc2InstanceKeyName"] = parsedFiltersResourceAwsEc2InstanceKeyName
					}
					if bodyFiltersResourceAwsEc2InstanceLaunchedAt != "" {
						var parsedFiltersResourceAwsEc2InstanceLaunchedAt any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsEc2InstanceLaunchedAt), &parsedFiltersResourceAwsEc2InstanceLaunchedAt); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-ec2-instance-launched-at JSON: %w", err)
						}
						nestedFilters["ResourceAwsEc2InstanceLaunchedAt"] = parsedFiltersResourceAwsEc2InstanceLaunchedAt
					}
					if bodyFiltersResourceAwsEc2InstanceSubnetId != "" {
						var parsedFiltersResourceAwsEc2InstanceSubnetId any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsEc2InstanceSubnetId), &parsedFiltersResourceAwsEc2InstanceSubnetId); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-ec2-instance-subnet-id JSON: %w", err)
						}
						nestedFilters["ResourceAwsEc2InstanceSubnetId"] = parsedFiltersResourceAwsEc2InstanceSubnetId
					}
					if bodyFiltersResourceAwsEc2InstanceType != "" {
						var parsedFiltersResourceAwsEc2InstanceType any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsEc2InstanceType), &parsedFiltersResourceAwsEc2InstanceType); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-ec2-instance-type JSON: %w", err)
						}
						nestedFilters["ResourceAwsEc2InstanceType"] = parsedFiltersResourceAwsEc2InstanceType
					}
					if bodyFiltersResourceAwsEc2InstanceVpcId != "" {
						var parsedFiltersResourceAwsEc2InstanceVpcId any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsEc2InstanceVpcId), &parsedFiltersResourceAwsEc2InstanceVpcId); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-ec2-instance-vpc-id JSON: %w", err)
						}
						nestedFilters["ResourceAwsEc2InstanceVpcId"] = parsedFiltersResourceAwsEc2InstanceVpcId
					}
					if bodyFiltersResourceAwsIamAccessKeyCreatedAt != "" {
						var parsedFiltersResourceAwsIamAccessKeyCreatedAt any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsIamAccessKeyCreatedAt), &parsedFiltersResourceAwsIamAccessKeyCreatedAt); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-iam-access-key-created-at JSON: %w", err)
						}
						nestedFilters["ResourceAwsIamAccessKeyCreatedAt"] = parsedFiltersResourceAwsIamAccessKeyCreatedAt
					}
					if bodyFiltersResourceAwsIamAccessKeyPrincipalName != "" {
						var parsedFiltersResourceAwsIamAccessKeyPrincipalName any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsIamAccessKeyPrincipalName), &parsedFiltersResourceAwsIamAccessKeyPrincipalName); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-iam-access-key-principal-name JSON: %w", err)
						}
						nestedFilters["ResourceAwsIamAccessKeyPrincipalName"] = parsedFiltersResourceAwsIamAccessKeyPrincipalName
					}
					if bodyFiltersResourceAwsIamAccessKeyStatus != "" {
						var parsedFiltersResourceAwsIamAccessKeyStatus any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsIamAccessKeyStatus), &parsedFiltersResourceAwsIamAccessKeyStatus); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-iam-access-key-status JSON: %w", err)
						}
						nestedFilters["ResourceAwsIamAccessKeyStatus"] = parsedFiltersResourceAwsIamAccessKeyStatus
					}
					if bodyFiltersResourceAwsIamAccessKeyUserName != "" {
						var parsedFiltersResourceAwsIamAccessKeyUserName any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsIamAccessKeyUserName), &parsedFiltersResourceAwsIamAccessKeyUserName); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-iam-access-key-user-name JSON: %w", err)
						}
						nestedFilters["ResourceAwsIamAccessKeyUserName"] = parsedFiltersResourceAwsIamAccessKeyUserName
					}
					if bodyFiltersResourceAwsIamUserUserName != "" {
						var parsedFiltersResourceAwsIamUserUserName any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsIamUserUserName), &parsedFiltersResourceAwsIamUserUserName); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-iam-user-user-name JSON: %w", err)
						}
						nestedFilters["ResourceAwsIamUserUserName"] = parsedFiltersResourceAwsIamUserUserName
					}
					if bodyFiltersResourceAwsS3BucketOwnerId != "" {
						var parsedFiltersResourceAwsS3BucketOwnerId any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsS3BucketOwnerId), &parsedFiltersResourceAwsS3BucketOwnerId); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-s3-bucket-owner-id JSON: %w", err)
						}
						nestedFilters["ResourceAwsS3BucketOwnerId"] = parsedFiltersResourceAwsS3BucketOwnerId
					}
					if bodyFiltersResourceAwsS3BucketOwnerName != "" {
						var parsedFiltersResourceAwsS3BucketOwnerName any
						if err := json.Unmarshal([]byte(bodyFiltersResourceAwsS3BucketOwnerName), &parsedFiltersResourceAwsS3BucketOwnerName); err != nil {
							return fmt.Errorf("parsing --filters-resource-aws-s3-bucket-owner-name JSON: %w", err)
						}
						nestedFilters["ResourceAwsS3BucketOwnerName"] = parsedFiltersResourceAwsS3BucketOwnerName
					}
					if bodyFiltersResourceContainerImageId != "" {
						var parsedFiltersResourceContainerImageId any
						if err := json.Unmarshal([]byte(bodyFiltersResourceContainerImageId), &parsedFiltersResourceContainerImageId); err != nil {
							return fmt.Errorf("parsing --filters-resource-container-image-id JSON: %w", err)
						}
						nestedFilters["ResourceContainerImageId"] = parsedFiltersResourceContainerImageId
					}
					if bodyFiltersResourceContainerImageName != "" {
						var parsedFiltersResourceContainerImageName any
						if err := json.Unmarshal([]byte(bodyFiltersResourceContainerImageName), &parsedFiltersResourceContainerImageName); err != nil {
							return fmt.Errorf("parsing --filters-resource-container-image-name JSON: %w", err)
						}
						nestedFilters["ResourceContainerImageName"] = parsedFiltersResourceContainerImageName
					}
					if bodyFiltersResourceContainerLaunchedAt != "" {
						var parsedFiltersResourceContainerLaunchedAt any
						if err := json.Unmarshal([]byte(bodyFiltersResourceContainerLaunchedAt), &parsedFiltersResourceContainerLaunchedAt); err != nil {
							return fmt.Errorf("parsing --filters-resource-container-launched-at JSON: %w", err)
						}
						nestedFilters["ResourceContainerLaunchedAt"] = parsedFiltersResourceContainerLaunchedAt
					}
					if bodyFiltersResourceContainerName != "" {
						var parsedFiltersResourceContainerName any
						if err := json.Unmarshal([]byte(bodyFiltersResourceContainerName), &parsedFiltersResourceContainerName); err != nil {
							return fmt.Errorf("parsing --filters-resource-container-name JSON: %w", err)
						}
						nestedFilters["ResourceContainerName"] = parsedFiltersResourceContainerName
					}
					if bodyFiltersResourceDetailsOther != "" {
						var parsedFiltersResourceDetailsOther any
						if err := json.Unmarshal([]byte(bodyFiltersResourceDetailsOther), &parsedFiltersResourceDetailsOther); err != nil {
							return fmt.Errorf("parsing --filters-resource-details-other JSON: %w", err)
						}
						nestedFilters["ResourceDetailsOther"] = parsedFiltersResourceDetailsOther
					}
					if bodyFiltersResourceId != "" {
						var parsedFiltersResourceId any
						if err := json.Unmarshal([]byte(bodyFiltersResourceId), &parsedFiltersResourceId); err != nil {
							return fmt.Errorf("parsing --filters-resource-id JSON: %w", err)
						}
						nestedFilters["ResourceId"] = parsedFiltersResourceId
					}
					if bodyFiltersResourcePartition != "" {
						var parsedFiltersResourcePartition any
						if err := json.Unmarshal([]byte(bodyFiltersResourcePartition), &parsedFiltersResourcePartition); err != nil {
							return fmt.Errorf("parsing --filters-resource-partition JSON: %w", err)
						}
						nestedFilters["ResourcePartition"] = parsedFiltersResourcePartition
					}
					if bodyFiltersResourceRegion != "" {
						var parsedFiltersResourceRegion any
						if err := json.Unmarshal([]byte(bodyFiltersResourceRegion), &parsedFiltersResourceRegion); err != nil {
							return fmt.Errorf("parsing --filters-resource-region JSON: %w", err)
						}
						nestedFilters["ResourceRegion"] = parsedFiltersResourceRegion
					}
					if bodyFiltersResourceTags != "" {
						var parsedFiltersResourceTags any
						if err := json.Unmarshal([]byte(bodyFiltersResourceTags), &parsedFiltersResourceTags); err != nil {
							return fmt.Errorf("parsing --filters-resource-tags JSON: %w", err)
						}
						nestedFilters["ResourceTags"] = parsedFiltersResourceTags
					}
					if bodyFiltersResourceType != "" {
						var parsedFiltersResourceType any
						if err := json.Unmarshal([]byte(bodyFiltersResourceType), &parsedFiltersResourceType); err != nil {
							return fmt.Errorf("parsing --filters-resource-type JSON: %w", err)
						}
						nestedFilters["ResourceType"] = parsedFiltersResourceType
					}
					if bodyFiltersSample != "" {
						var parsedFiltersSample any
						if err := json.Unmarshal([]byte(bodyFiltersSample), &parsedFiltersSample); err != nil {
							return fmt.Errorf("parsing --filters-sample JSON: %w", err)
						}
						nestedFilters["Sample"] = parsedFiltersSample
					}
					if bodyFiltersSeverityLabel != "" {
						var parsedFiltersSeverityLabel any
						if err := json.Unmarshal([]byte(bodyFiltersSeverityLabel), &parsedFiltersSeverityLabel); err != nil {
							return fmt.Errorf("parsing --filters-severity-label JSON: %w", err)
						}
						nestedFilters["SeverityLabel"] = parsedFiltersSeverityLabel
					}
					if bodyFiltersSeverityNormalized != "" {
						var parsedFiltersSeverityNormalized any
						if err := json.Unmarshal([]byte(bodyFiltersSeverityNormalized), &parsedFiltersSeverityNormalized); err != nil {
							return fmt.Errorf("parsing --filters-severity-normalized JSON: %w", err)
						}
						nestedFilters["SeverityNormalized"] = parsedFiltersSeverityNormalized
					}
					if bodyFiltersSeverityProduct != "" {
						var parsedFiltersSeverityProduct any
						if err := json.Unmarshal([]byte(bodyFiltersSeverityProduct), &parsedFiltersSeverityProduct); err != nil {
							return fmt.Errorf("parsing --filters-severity-product JSON: %w", err)
						}
						nestedFilters["SeverityProduct"] = parsedFiltersSeverityProduct
					}
					if bodyFiltersSourceUrl != "" {
						var parsedFiltersSourceUrl any
						if err := json.Unmarshal([]byte(bodyFiltersSourceUrl), &parsedFiltersSourceUrl); err != nil {
							return fmt.Errorf("parsing --filters-source-url JSON: %w", err)
						}
						nestedFilters["SourceUrl"] = parsedFiltersSourceUrl
					}
					if bodyFiltersThreatIntelIndicatorCategory != "" {
						var parsedFiltersThreatIntelIndicatorCategory any
						if err := json.Unmarshal([]byte(bodyFiltersThreatIntelIndicatorCategory), &parsedFiltersThreatIntelIndicatorCategory); err != nil {
							return fmt.Errorf("parsing --filters-threat-intel-indicator-category JSON: %w", err)
						}
						nestedFilters["ThreatIntelIndicatorCategory"] = parsedFiltersThreatIntelIndicatorCategory
					}
					if bodyFiltersThreatIntelIndicatorLastObservedAt != "" {
						var parsedFiltersThreatIntelIndicatorLastObservedAt any
						if err := json.Unmarshal([]byte(bodyFiltersThreatIntelIndicatorLastObservedAt), &parsedFiltersThreatIntelIndicatorLastObservedAt); err != nil {
							return fmt.Errorf("parsing --filters-threat-intel-indicator-last-observed-at JSON: %w", err)
						}
						nestedFilters["ThreatIntelIndicatorLastObservedAt"] = parsedFiltersThreatIntelIndicatorLastObservedAt
					}
					if bodyFiltersThreatIntelIndicatorSource != "" {
						var parsedFiltersThreatIntelIndicatorSource any
						if err := json.Unmarshal([]byte(bodyFiltersThreatIntelIndicatorSource), &parsedFiltersThreatIntelIndicatorSource); err != nil {
							return fmt.Errorf("parsing --filters-threat-intel-indicator-source JSON: %w", err)
						}
						nestedFilters["ThreatIntelIndicatorSource"] = parsedFiltersThreatIntelIndicatorSource
					}
					if bodyFiltersThreatIntelIndicatorSourceUrl != "" {
						var parsedFiltersThreatIntelIndicatorSourceUrl any
						if err := json.Unmarshal([]byte(bodyFiltersThreatIntelIndicatorSourceUrl), &parsedFiltersThreatIntelIndicatorSourceUrl); err != nil {
							return fmt.Errorf("parsing --filters-threat-intel-indicator-source-url JSON: %w", err)
						}
						nestedFilters["ThreatIntelIndicatorSourceUrl"] = parsedFiltersThreatIntelIndicatorSourceUrl
					}
					if bodyFiltersThreatIntelIndicatorType != "" {
						var parsedFiltersThreatIntelIndicatorType any
						if err := json.Unmarshal([]byte(bodyFiltersThreatIntelIndicatorType), &parsedFiltersThreatIntelIndicatorType); err != nil {
							return fmt.Errorf("parsing --filters-threat-intel-indicator-type JSON: %w", err)
						}
						nestedFilters["ThreatIntelIndicatorType"] = parsedFiltersThreatIntelIndicatorType
					}
					if bodyFiltersThreatIntelIndicatorValue != "" {
						var parsedFiltersThreatIntelIndicatorValue any
						if err := json.Unmarshal([]byte(bodyFiltersThreatIntelIndicatorValue), &parsedFiltersThreatIntelIndicatorValue); err != nil {
							return fmt.Errorf("parsing --filters-threat-intel-indicator-value JSON: %w", err)
						}
						nestedFilters["ThreatIntelIndicatorValue"] = parsedFiltersThreatIntelIndicatorValue
					}
					if bodyFiltersTitle != "" {
						var parsedFiltersTitle any
						if err := json.Unmarshal([]byte(bodyFiltersTitle), &parsedFiltersTitle); err != nil {
							return fmt.Errorf("parsing --filters-title JSON: %w", err)
						}
						nestedFilters["Title"] = parsedFiltersTitle
					}
					if bodyFiltersType != "" {
						var parsedFiltersType any
						if err := json.Unmarshal([]byte(bodyFiltersType), &parsedFiltersType); err != nil {
							return fmt.Errorf("parsing --filters-type JSON: %w", err)
						}
						nestedFilters["Type"] = parsedFiltersType
					}
					if bodyFiltersUpdatedAt != "" {
						var parsedFiltersUpdatedAt any
						if err := json.Unmarshal([]byte(bodyFiltersUpdatedAt), &parsedFiltersUpdatedAt); err != nil {
							return fmt.Errorf("parsing --filters-updated-at JSON: %w", err)
						}
						nestedFilters["UpdatedAt"] = parsedFiltersUpdatedAt
					}
					if bodyFiltersUserDefinedFields != "" {
						var parsedFiltersUserDefinedFields any
						if err := json.Unmarshal([]byte(bodyFiltersUserDefinedFields), &parsedFiltersUserDefinedFields); err != nil {
							return fmt.Errorf("parsing --filters-user-defined-fields JSON: %w", err)
						}
						nestedFilters["UserDefinedFields"] = parsedFiltersUserDefinedFields
					}
					if bodyFiltersVerificationState != "" {
						var parsedFiltersVerificationState any
						if err := json.Unmarshal([]byte(bodyFiltersVerificationState), &parsedFiltersVerificationState); err != nil {
							return fmt.Errorf("parsing --filters-verification-state JSON: %w", err)
						}
						nestedFilters["VerificationState"] = parsedFiltersVerificationState
					}
					if bodyFiltersWorkflowState != "" {
						var parsedFiltersWorkflowState any
						if err := json.Unmarshal([]byte(bodyFiltersWorkflowState), &parsedFiltersWorkflowState); err != nil {
							return fmt.Errorf("parsing --filters-workflow-state JSON: %w", err)
						}
						nestedFilters["WorkflowState"] = parsedFiltersWorkflowState
					}
					if bodyFiltersWorkflowStatus != "" {
						var parsedFiltersWorkflowStatus any
						if err := json.Unmarshal([]byte(bodyFiltersWorkflowStatus), &parsedFiltersWorkflowStatus); err != nil {
							return fmt.Errorf("parsing --filters-workflow-status JSON: %w", err)
						}
						nestedFilters["WorkflowStatus"] = parsedFiltersWorkflowStatus
					}
					if len(nestedFilters) > 0 {
						body["Filters"] = nestedFilters
					}
				}
				if bodyGroupByAttribute != "" {
					body["GroupByAttribute"] = bodyGroupByAttribute
				}
				if bodyName != "" {
					body["Name"] = bodyName
				}
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "insights",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyFiltersAwsAccountId, "filters-aws-account-id", "", "Aws account id")
	cmd.Flags().StringVar(&bodyFiltersCompanyName, "filters-company-name", "", "Company name")
	cmd.Flags().StringVar(&bodyFiltersComplianceAssociatedStandardsId, "filters-compliance-associated-standards-id", "", "Compliance associated standards id")
	cmd.Flags().StringVar(&bodyFiltersComplianceSecurityControlId, "filters-compliance-security-control-id", "", "Compliance security control id")
	cmd.Flags().StringVar(&bodyFiltersComplianceStatus, "filters-compliance-status", "", "Compliance status")
	cmd.Flags().StringVar(&bodyFiltersConfidence, "filters-confidence", "", "Confidence")
	cmd.Flags().StringVar(&bodyFiltersCreatedAt, "filters-created-at", "", "Created at")
	cmd.Flags().StringVar(&bodyFiltersCriticality, "filters-criticality", "", "Criticality")
	cmd.Flags().StringVar(&bodyFiltersDescription, "filters-description", "", "Description")
	cmd.Flags().StringVar(&bodyFiltersFindingProviderFieldsConfidence, "filters-finding-provider-fields-confidence", "", "Finding provider fields confidence")
	cmd.Flags().StringVar(&bodyFiltersFindingProviderFieldsCriticality, "filters-finding-provider-fields-criticality", "", "Finding provider fields criticality")
	cmd.Flags().StringVar(&bodyFiltersFindingProviderFieldsRelatedFindingsId, "filters-finding-provider-fields-related-findings-id", "", "Finding provider fields related findings id")
	cmd.Flags().StringVar(&bodyFiltersFindingProviderFieldsRelatedFindingsProductArn, "filters-finding-provider-fields-related-findings-product-arn", "", "Finding provider fields related findings product arn")
	cmd.Flags().StringVar(&bodyFiltersFindingProviderFieldsSeverityLabel, "filters-finding-provider-fields-severity-label", "", "Finding provider fields severity label")
	cmd.Flags().StringVar(&bodyFiltersFindingProviderFieldsSeverityOriginal, "filters-finding-provider-fields-severity-original", "", "Finding provider fields severity original")
	cmd.Flags().StringVar(&bodyFiltersFindingProviderFieldsTypes, "filters-finding-provider-fields-types", "", "Finding provider fields types")
	cmd.Flags().StringVar(&bodyFiltersFirstObservedAt, "filters-first-observed-at", "", "First observed at")
	cmd.Flags().StringVar(&bodyFiltersGeneratorId, "filters-generator-id", "", "Generator id")
	cmd.Flags().StringVar(&bodyFiltersId, "filters-id", "", "Id")
	cmd.Flags().StringVar(&bodyFiltersKeyword, "filters-keyword", "", "Keyword")
	cmd.Flags().StringVar(&bodyFiltersLastObservedAt, "filters-last-observed-at", "", "Last observed at")
	cmd.Flags().StringVar(&bodyFiltersMalwareName, "filters-malware-name", "", "Malware name")
	cmd.Flags().StringVar(&bodyFiltersMalwarePath, "filters-malware-path", "", "Malware path")
	cmd.Flags().StringVar(&bodyFiltersMalwareState, "filters-malware-state", "", "Malware state")
	cmd.Flags().StringVar(&bodyFiltersMalwareType, "filters-malware-type", "", "Malware type")
	cmd.Flags().StringVar(&bodyFiltersNetworkDestinationDomain, "filters-network-destination-domain", "", "Network destination domain")
	cmd.Flags().StringVar(&bodyFiltersNetworkDestinationIpV4, "filters-network-destination-ip-v4", "", "Network destination ip v4")
	cmd.Flags().StringVar(&bodyFiltersNetworkDestinationIpV6, "filters-network-destination-ip-v6", "", "Network destination ip v6")
	cmd.Flags().StringVar(&bodyFiltersNetworkDestinationPort, "filters-network-destination-port", "", "Network destination port")
	cmd.Flags().StringVar(&bodyFiltersNetworkDirection, "filters-network-direction", "", "Network direction")
	cmd.Flags().StringVar(&bodyFiltersNetworkProtocol, "filters-network-protocol", "", "Network protocol")
	cmd.Flags().StringVar(&bodyFiltersNetworkSourceDomain, "filters-network-source-domain", "", "Network source domain")
	cmd.Flags().StringVar(&bodyFiltersNetworkSourceIpV4, "filters-network-source-ip-v4", "", "Network source ip v4")
	cmd.Flags().StringVar(&bodyFiltersNetworkSourceIpV6, "filters-network-source-ip-v6", "", "Network source ip v6")
	cmd.Flags().StringVar(&bodyFiltersNetworkSourceMac, "filters-network-source-mac", "", "Network source mac")
	cmd.Flags().StringVar(&bodyFiltersNetworkSourcePort, "filters-network-source-port", "", "Network source port")
	cmd.Flags().StringVar(&bodyFiltersNoteText, "filters-note-text", "", "Note text")
	cmd.Flags().StringVar(&bodyFiltersNoteUpdatedAt, "filters-note-updated-at", "", "Note updated at")
	cmd.Flags().StringVar(&bodyFiltersNoteUpdatedBy, "filters-note-updated-by", "", "Note updated by")
	cmd.Flags().StringVar(&bodyFiltersProcessLaunchedAt, "filters-process-launched-at", "", "Process launched at")
	cmd.Flags().StringVar(&bodyFiltersProcessName, "filters-process-name", "", "Process name")
	cmd.Flags().StringVar(&bodyFiltersProcessParentPid, "filters-process-parent-pid", "", "Process parent pid")
	cmd.Flags().StringVar(&bodyFiltersProcessPath, "filters-process-path", "", "Process path")
	cmd.Flags().StringVar(&bodyFiltersProcessPid, "filters-process-pid", "", "Process pid")
	cmd.Flags().StringVar(&bodyFiltersProcessTerminatedAt, "filters-process-terminated-at", "", "Process terminated at")
	cmd.Flags().StringVar(&bodyFiltersProductArn, "filters-product-arn", "", "Product arn")
	cmd.Flags().StringVar(&bodyFiltersProductFields, "filters-product-fields", "", "Product fields")
	cmd.Flags().StringVar(&bodyFiltersProductName, "filters-product-name", "", "Product name")
	cmd.Flags().StringVar(&bodyFiltersRecommendationText, "filters-recommendation-text", "", "Recommendation text")
	cmd.Flags().StringVar(&bodyFiltersRecordState, "filters-record-state", "", "Record state")
	cmd.Flags().StringVar(&bodyFiltersRegion, "filters-region", "", "Region")
	cmd.Flags().StringVar(&bodyFiltersRelatedFindingsId, "filters-related-findings-id", "", "Related findings id")
	cmd.Flags().StringVar(&bodyFiltersRelatedFindingsProductArn, "filters-related-findings-product-arn", "", "Related findings product arn")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsEc2InstanceIamInstanceProfileArn, "filters-resource-aws-ec2-instance-iam-instance-profile-arn", "", "Resource aws ec2 instance iam instance profile arn")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsEc2InstanceImageId, "filters-resource-aws-ec2-instance-image-id", "", "Resource aws ec2 instance image id")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsEc2InstanceIpV4Addresses, "filters-resource-aws-ec2-instance-ip-v4-addresses", "", "Resource aws ec2 instance ip v4 addresses")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsEc2InstanceIpV6Addresses, "filters-resource-aws-ec2-instance-ip-v6-addresses", "", "Resource aws ec2 instance ip v6 addresses")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsEc2InstanceKeyName, "filters-resource-aws-ec2-instance-key-name", "", "Resource aws ec2 instance key name")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsEc2InstanceLaunchedAt, "filters-resource-aws-ec2-instance-launched-at", "", "Resource aws ec2 instance launched at")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsEc2InstanceSubnetId, "filters-resource-aws-ec2-instance-subnet-id", "", "Resource aws ec2 instance subnet id")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsEc2InstanceType, "filters-resource-aws-ec2-instance-type", "", "Resource aws ec2 instance type")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsEc2InstanceVpcId, "filters-resource-aws-ec2-instance-vpc-id", "", "Resource aws ec2 instance vpc id")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsIamAccessKeyCreatedAt, "filters-resource-aws-iam-access-key-created-at", "", "Resource aws iam access key created at")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsIamAccessKeyPrincipalName, "filters-resource-aws-iam-access-key-principal-name", "", "Resource aws iam access key principal name")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsIamAccessKeyStatus, "filters-resource-aws-iam-access-key-status", "", "Resource aws iam access key status")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsIamAccessKeyUserName, "filters-resource-aws-iam-access-key-user-name", "", "Resource aws iam access key user name")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsIamUserUserName, "filters-resource-aws-iam-user-user-name", "", "Resource aws iam user user name")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsS3BucketOwnerId, "filters-resource-aws-s3-bucket-owner-id", "", "Resource aws s3 bucket owner id")
	cmd.Flags().StringVar(&bodyFiltersResourceAwsS3BucketOwnerName, "filters-resource-aws-s3-bucket-owner-name", "", "Resource aws s3 bucket owner name")
	cmd.Flags().StringVar(&bodyFiltersResourceContainerImageId, "filters-resource-container-image-id", "", "Resource container image id")
	cmd.Flags().StringVar(&bodyFiltersResourceContainerImageName, "filters-resource-container-image-name", "", "Resource container image name")
	cmd.Flags().StringVar(&bodyFiltersResourceContainerLaunchedAt, "filters-resource-container-launched-at", "", "Resource container launched at")
	cmd.Flags().StringVar(&bodyFiltersResourceContainerName, "filters-resource-container-name", "", "Resource container name")
	cmd.Flags().StringVar(&bodyFiltersResourceDetailsOther, "filters-resource-details-other", "", "Resource details other")
	cmd.Flags().StringVar(&bodyFiltersResourceId, "filters-resource-id", "", "Resource id")
	cmd.Flags().StringVar(&bodyFiltersResourcePartition, "filters-resource-partition", "", "Resource partition")
	cmd.Flags().StringVar(&bodyFiltersResourceRegion, "filters-resource-region", "", "Resource region")
	cmd.Flags().StringVar(&bodyFiltersResourceTags, "filters-resource-tags", "", "Resource tags")
	cmd.Flags().StringVar(&bodyFiltersResourceType, "filters-resource-type", "", "Resource type")
	cmd.Flags().StringVar(&bodyFiltersSample, "filters-sample", "", "Sample")
	cmd.Flags().StringVar(&bodyFiltersSeverityLabel, "filters-severity-label", "", "Severity label")
	cmd.Flags().StringVar(&bodyFiltersSeverityNormalized, "filters-severity-normalized", "", "Severity normalized")
	cmd.Flags().StringVar(&bodyFiltersSeverityProduct, "filters-severity-product", "", "Severity product")
	cmd.Flags().StringVar(&bodyFiltersSourceUrl, "filters-source-url", "", "Source url")
	cmd.Flags().StringVar(&bodyFiltersThreatIntelIndicatorCategory, "filters-threat-intel-indicator-category", "", "Threat intel indicator category")
	cmd.Flags().StringVar(&bodyFiltersThreatIntelIndicatorLastObservedAt, "filters-threat-intel-indicator-last-observed-at", "", "Threat intel indicator last observed at")
	cmd.Flags().StringVar(&bodyFiltersThreatIntelIndicatorSource, "filters-threat-intel-indicator-source", "", "Threat intel indicator source")
	cmd.Flags().StringVar(&bodyFiltersThreatIntelIndicatorSourceUrl, "filters-threat-intel-indicator-source-url", "", "Threat intel indicator source url")
	cmd.Flags().StringVar(&bodyFiltersThreatIntelIndicatorType, "filters-threat-intel-indicator-type", "", "Threat intel indicator type")
	cmd.Flags().StringVar(&bodyFiltersThreatIntelIndicatorValue, "filters-threat-intel-indicator-value", "", "Threat intel indicator value")
	cmd.Flags().StringVar(&bodyFiltersTitle, "filters-title", "", "Title")
	cmd.Flags().StringVar(&bodyFiltersType, "filters-type", "", "Type")
	cmd.Flags().StringVar(&bodyFiltersUpdatedAt, "filters-updated-at", "", "Updated at")
	cmd.Flags().StringVar(&bodyFiltersUserDefinedFields, "filters-user-defined-fields", "", "User defined fields")
	cmd.Flags().StringVar(&bodyFiltersVerificationState, "filters-verification-state", "", "Verification state")
	cmd.Flags().StringVar(&bodyFiltersWorkflowState, "filters-workflow-state", "", "Workflow state")
	cmd.Flags().StringVar(&bodyFiltersWorkflowStatus, "filters-workflow-status", "", "Workflow status")
	cmd.Flags().StringVar(&bodyGroupByAttribute, "group-by-attribute", "", "The attribute used to group the findings for the insight. The grouping attribute identifies the type of item that...")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the custom insight to create.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
