// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetAwsbudgetServiceGatewayUpdateNotificationPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAccountId string
	var bodyBudgetName string
	var bodyNewNotificationComparisonOperator string
	var bodyNewNotificationNotificationState string
	var bodyNewNotificationNotificationType string
	var bodyNewNotificationThreshold float64
	var bodyNewNotificationThresholdType string
	var bodyOldNotificationComparisonOperator string
	var bodyOldNotificationNotificationState string
	var bodyOldNotificationNotificationType string
	var bodyOldNotificationThreshold float64
	var bodyOldNotificationThresholdType string

	cmd := &cobra.Command{
		Use:         "x-amz-target-awsbudget-service-gateway-update-notification",
		Short:       "Updates a notification.",
		Long:        "Shortcut for 'x-amz-target-awsbudget-service-gateway-update-notification update-notification'. Updates a notification.",
		Example:     "  aws-pp-pp-cli x-amz-target-awsbudget-service-gateway-update-notification --account-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-awsbudget-service-gateway-update-notification.update-notification", "pp:method": "POST", "pp:path": "https://budgets.amazonaws.com/#X-Amz-Target=AWSBudgetServiceGateway.UpdateNotification"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("account-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "account-id")
			}
			if !cmd.Flags().Changed("budget-name") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "budget-name")
			}
			if !cmd.Flags().Changed("new-notification-comparison-operator") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "new-notification-comparison-operator")
			}
			if !cmd.Flags().Changed("new-notification-notification-type") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "new-notification-notification-type")
			}
			if !cmd.Flags().Changed("new-notification-threshold") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "new-notification-threshold")
			}
			if !cmd.Flags().Changed("old-notification-comparison-operator") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "old-notification-comparison-operator")
			}
			if !cmd.Flags().Changed("old-notification-notification-type") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "old-notification-notification-type")
			}
			if !cmd.Flags().Changed("old-notification-threshold") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "old-notification-threshold")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://budgets.amazonaws.com/#X-Amz-Target=AWSBudgetServiceGateway.UpdateNotification"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAccountId != "" {
				body["AccountId"] = bodyAccountId
			}
			if bodyBudgetName != "" {
				body["BudgetName"] = bodyBudgetName
			}
			{
				nestedNewNotification := map[string]any{}
				if bodyNewNotificationComparisonOperator != "" {
					nestedNewNotification["ComparisonOperator"] = bodyNewNotificationComparisonOperator
				}
				if bodyNewNotificationNotificationState != "" {
					nestedNewNotification["NotificationState"] = bodyNewNotificationNotificationState
				}
				if bodyNewNotificationNotificationType != "" {
					nestedNewNotification["NotificationType"] = bodyNewNotificationNotificationType
				}
				if bodyNewNotificationThreshold != 0.0 {
					nestedNewNotification["Threshold"] = bodyNewNotificationThreshold
				}
				if bodyNewNotificationThresholdType != "" {
					nestedNewNotification["ThresholdType"] = bodyNewNotificationThresholdType
				}
				if len(nestedNewNotification) > 0 {
					body["NewNotification"] = nestedNewNotification
				}
			}
			{
				nestedOldNotification := map[string]any{}
				if bodyOldNotificationComparisonOperator != "" {
					nestedOldNotification["ComparisonOperator"] = bodyOldNotificationComparisonOperator
				}
				if bodyOldNotificationNotificationState != "" {
					nestedOldNotification["NotificationState"] = bodyOldNotificationNotificationState
				}
				if bodyOldNotificationNotificationType != "" {
					nestedOldNotification["NotificationType"] = bodyOldNotificationNotificationType
				}
				if bodyOldNotificationThreshold != 0.0 {
					nestedOldNotification["Threshold"] = bodyOldNotificationThreshold
				}
				if bodyOldNotificationThresholdType != "" {
					nestedOldNotification["ThresholdType"] = bodyOldNotificationThresholdType
				}
				if len(nestedOldNotification) > 0 {
					body["OldNotification"] = nestedOldNotification
				}
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAccountId, "account-id", "", "The account ID of the user. It's a 12-digit number.")
	cmd.Flags().StringVar(&bodyBudgetName, "budget-name", "", "A string that represents the budget name. The ':' and '' characters aren't allowed.")
	cmd.Flags().StringVar(&bodyNewNotificationComparisonOperator, "new-notification-comparison-operator", "", "<p> The comparison operator of a notification. Currently, the service supports the following operators:</p> <p>...")
	cmd.Flags().StringVar(&bodyNewNotificationNotificationState, "new-notification-notification-state", "", "Notification state")
	cmd.Flags().StringVar(&bodyNewNotificationNotificationType, "new-notification-notification-type", "", "The type of a notification. It must be ACTUAL or FORECASTED.")
	cmd.Flags().Float64Var(&bodyNewNotificationThreshold, "new-notification-threshold", 0.0, "The threshold of a notification.")
	cmd.Flags().StringVar(&bodyNewNotificationThresholdType, "new-notification-threshold-type", "", "The type of threshold for a notification.")
	cmd.Flags().StringVar(&bodyOldNotificationComparisonOperator, "old-notification-comparison-operator", "", "<p> The comparison operator of a notification. Currently, the service supports the following operators:</p> <p>...")
	cmd.Flags().StringVar(&bodyOldNotificationNotificationState, "old-notification-notification-state", "", "Notification state")
	cmd.Flags().StringVar(&bodyOldNotificationNotificationType, "old-notification-notification-type", "", "The type of a notification. It must be ACTUAL or FORECASTED.")
	cmd.Flags().Float64Var(&bodyOldNotificationThreshold, "old-notification-threshold", 0.0, "The threshold of a notification.")
	cmd.Flags().StringVar(&bodyOldNotificationThresholdType, "old-notification-threshold-type", "", "The type of threshold for a notification.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
