// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetStarlingDoveServiceDescribeConformancePackCompliancePromotedCmd(flags *rootFlags) *cobra.Command {
	var flagLimit string
	var flagNextToken string
	var bodyConformancePackName string
	var bodyFiltersComplianceType string
	var bodyFiltersConfigRuleNames string

	cmd := &cobra.Command{
		Use:         "x-amz-target-starling-dove-service-describe-conformance-pack-compliance",
		Short:       "<p>Returns compliance details for each rule in that conformance pack.</p> <note> <p>You must provide exact rule...",
		Long:        "Shortcut for 'x-amz-target-starling-dove-service-describe-conformance-pack-compliance describe-conformance-pack-compliance'. <p>Returns compliance details for each rule in that conformance pack.</p> <note> <p>You must provide exact rule...",
		Example:     "  aws-pp-pp-cli x-amz-target-starling-dove-service-describe-conformance-pack-compliance --conformance-pack-name example-resource",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-starling-dove-service-describe-conformance-pack-compliance.describe-conformance-pack-compliance", "pp:method": "POST", "pp:path": "http://config.us-east-1.amazonaws.com/#X-Amz-Target=StarlingDoveService.DescribeConformancePackCompliance"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("conformance-pack-name") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "conformance-pack-name")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://config.us-east-1.amazonaws.com/#X-Amz-Target=StarlingDoveService.DescribeConformancePackCompliance"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyConformancePackName != "" {
				body["ConformancePackName"] = bodyConformancePackName
			}
			{
				nestedFilters := map[string]any{}
				if bodyFiltersComplianceType != "" {
					nestedFilters["ComplianceType"] = bodyFiltersComplianceType
				}
				if bodyFiltersConfigRuleNames != "" {
					var parsedFiltersConfigRuleNames any
					if err := json.Unmarshal([]byte(bodyFiltersConfigRuleNames), &parsedFiltersConfigRuleNames); err != nil {
						return fmt.Errorf("parsing --filters-config-rule-names JSON: %w", err)
					}
					nestedFilters["ConfigRuleNames"] = parsedFiltersConfigRuleNames
				}
				if len(nestedFilters) > 0 {
					body["Filters"] = nestedFilters
				}
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagLimit, "limit", "", "Pagination limit")
	cmd.Flags().StringVar(&flagNextToken, "next-token", "", "Pagination token")
	cmd.Flags().StringVar(&bodyConformancePackName, "conformance-pack-name", "", "Conformance pack name")
	cmd.Flags().StringVar(&bodyFiltersComplianceType, "filters-compliance-type", "", "Compliance type")
	cmd.Flags().StringVar(&bodyFiltersConfigRuleNames, "filters-config-rule-names", "", "Config rule names")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
