// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetAwssupport20130415DescribeCasesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagMaxResults string
	var flagNextToken string
	var bodyAfterTime string
	var bodyBeforeTime string
	var bodyCaseIdList string
	var bodyDisplayId string
	var bodyIncludeCommunications bool
	var bodyIncludeResolvedCases bool
	var bodyLanguage string

	cmd := &cobra.Command{
		Use:         "x-amz-target-awssupport-20130415-describe-cases",
		Short:       "<p>Returns a list of cases that you specify by passing one or more case IDs. You can use the <code>afterTime</code>...",
		Long:        "Shortcut for 'x-amz-target-awssupport-20130415-describe-cases describe-cases'. <p>Returns a list of cases that you specify by passing one or more case IDs. You can use the <code>afterTime</code>...",
		Example:     "  aws-pp-pp-cli x-amz-target-awssupport-20130415-describe-cases",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-awssupport-20130415-describe-cases.describe-cases", "pp:method": "POST", "pp:path": "https://support.us-east-1.amazonaws.com/#X-Amz-Target=AWSSupport_20130415.DescribeCases"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://support.us-east-1.amazonaws.com/#X-Amz-Target=AWSSupport_20130415.DescribeCases"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAfterTime != "" {
				body["afterTime"] = bodyAfterTime
			}
			if bodyBeforeTime != "" {
				body["beforeTime"] = bodyBeforeTime
			}
			if bodyCaseIdList != "" {
				var parsedCaseIdList any
				if err := json.Unmarshal([]byte(bodyCaseIdList), &parsedCaseIdList); err != nil {
					return fmt.Errorf("parsing --case-id-list JSON: %w", err)
				}
				body["caseIdList"] = parsedCaseIdList
			}
			if bodyDisplayId != "" {
				body["displayId"] = bodyDisplayId
			}
			if bodyIncludeCommunications != false {
				body["includeCommunications"] = bodyIncludeCommunications
			}
			if bodyIncludeResolvedCases != false {
				body["includeResolvedCases"] = bodyIncludeResolvedCases
			}
			if bodyLanguage != "" {
				body["language"] = bodyLanguage
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagMaxResults, "max-results", "", "Pagination limit")
	cmd.Flags().StringVar(&flagNextToken, "next-token", "", "Pagination token")
	cmd.Flags().StringVar(&bodyAfterTime, "after-time", "", "After time")
	cmd.Flags().StringVar(&bodyBeforeTime, "before-time", "", "Before time")
	cmd.Flags().StringVar(&bodyCaseIdList, "case-id-list", "", "Case id list")
	cmd.Flags().StringVar(&bodyDisplayId, "display-id", "", "Display id")
	cmd.Flags().BoolVar(&bodyIncludeCommunications, "include-communications", false, "Include communications")
	cmd.Flags().BoolVar(&bodyIncludeResolvedCases, "include-resolved-cases", false, "Include resolved cases")
	cmd.Flags().StringVar(&bodyLanguage, "language", "", "Language")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
