// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101RemoveTagsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyResourceId string
	var bodyTagsList string

	cmd := &cobra.Command{
		Use:         "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-remove-tags",
		Short:       "Removes the specified tags from a trail, event data store, or channel.",
		Long:        "Shortcut for 'x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-remove-tags remove-tags'. Removes the specified tags from a trail, event data store, or channel.",
		Example:     "  aws-pp-pp-cli x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-remove-tags --resource-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-remove-tags.remove-tags", "pp:method": "POST", "pp:path": "http://cloudtrail.us-east-1.amazonaws.com/#X-Amz-Target=com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.RemoveTags"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("resource-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "resource-id")
			}
			if !cmd.Flags().Changed("tags-list") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "tags-list")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://cloudtrail.us-east-1.amazonaws.com/#X-Amz-Target=com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.RemoveTags"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyResourceId != "" {
				body["ResourceId"] = bodyResourceId
			}
			if bodyTagsList != "" {
				var parsedTagsList any
				if err := json.Unmarshal([]byte(bodyTagsList), &parsedTagsList); err != nil {
					return fmt.Errorf("parsing --tags-list JSON: %w", err)
				}
				body["TagsList"] = parsedTagsList
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyResourceId, "resource-id", "", "Resource id")
	cmd.Flags().StringVar(&bodyTagsList, "tags-list", "", "A list of tags.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
