// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetComputeOptimizerServiceGetEcsserviceRecommendationsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAccountIds string
	var bodyFilters string
	var bodyMaxResults int
	var bodyNextToken string
	var bodyServiceArns string

	cmd := &cobra.Command{
		Use:         "x-amz-target-compute-optimizer-service-get-ecsservice-recommendations",
		Short:       "<p> Returns Amazon ECS service recommendations. </p> <p> Compute Optimizer generates recommendations for Amazon ECS...",
		Long:        "Shortcut for 'x-amz-target-compute-optimizer-service-get-ecsservice-recommendations get-ecsservice-recommendations'. <p> Returns Amazon ECS service recommendations. </p> <p> Compute Optimizer generates recommendations for Amazon ECS...",
		Example:     "  aws-pp-pp-cli x-amz-target-compute-optimizer-service-get-ecsservice-recommendations",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-compute-optimizer-service-get-ecsservice-recommendations.get-ecsservice-recommendations", "pp:method": "POST", "pp:path": "http://compute-optimizer.us-east-1.amazonaws.com/#X-Amz-Target=ComputeOptimizerService.GetECSServiceRecommendations"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://compute-optimizer.us-east-1.amazonaws.com/#X-Amz-Target=ComputeOptimizerService.GetECSServiceRecommendations"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAccountIds != "" {
				var parsedAccountIds any
				if err := json.Unmarshal([]byte(bodyAccountIds), &parsedAccountIds); err != nil {
					return fmt.Errorf("parsing --account-ids JSON: %w", err)
				}
				body["accountIds"] = parsedAccountIds
			}
			if bodyFilters != "" {
				var parsedFilters any
				if err := json.Unmarshal([]byte(bodyFilters), &parsedFilters); err != nil {
					return fmt.Errorf("parsing --filters JSON: %w", err)
				}
				body["filters"] = parsedFilters
			}
			if bodyMaxResults != 0 {
				body["maxResults"] = bodyMaxResults
			}
			if bodyNextToken != "" {
				body["nextToken"] = bodyNextToken
			}
			if bodyServiceArns != "" {
				var parsedServiceArns any
				if err := json.Unmarshal([]byte(bodyServiceArns), &parsedServiceArns); err != nil {
					return fmt.Errorf("parsing --service-arns JSON: %w", err)
				}
				body["serviceArns"] = parsedServiceArns
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAccountIds, "account-ids", "", "Account ids")
	cmd.Flags().StringVar(&bodyFilters, "filters", "", "Filters")
	cmd.Flags().IntVar(&bodyMaxResults, "max-results", 0, "Max results")
	cmd.Flags().StringVar(&bodyNextToken, "next-token", "", "Next token")
	cmd.Flags().StringVar(&bodyServiceArns, "service-arns", "", "Service arns")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
