// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAssociationsSecurityControlIdPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagSecurityControlId string
	var flagNextToken string
	var flagMaxResults int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "associations-security-control-id",
		Short:       "Specifies whether a control is currently enabled or disabled in each enabled standard in the calling account.",
		Long:        "Shortcut for 'associations-security-control-id list-standards-control-associations'. Specifies whether a control is currently enabled or disabled in each enabled standard in the calling account.",
		Example:     "  aws-pp-pp-cli associations-security-control-id --security-control-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "associations-security-control-id.list-standards-control-associations", "pp:method": "GET", "pp:path": "http://securityhub.us-east-1.amazonaws.com/associations#SecurityControlId", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("security-control-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "security-control-id")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://securityhub.us-east-1.amazonaws.com/associations#SecurityControlId"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "associations-security-control-id", path, map[string]string{
				"SecurityControlId": fmt.Sprintf("%v", flagSecurityControlId),
				"NextToken":         fmt.Sprintf("%v", flagNextToken),
				"MaxResults":        fmt.Sprintf("%v", flagMaxResults),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSecurityControlId, "security-control-id", "", "The identifier of the control (identified with <code>SecurityControlId</code>, <code>SecurityControlArn</code>, or a...")
	cmd.Flags().StringVar(&flagNextToken, "next-token", "", "Optional pagination parameter.")
	cmd.Flags().IntVar(&flagMaxResults, "max-results", 0, "An optional parameter that limits the total results of the API response to the specified number. If this parameter...")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
