// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetAwsinsightsIndexServiceCreateCostCategoryDefinitionPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyDefaultValue string
	var bodyEffectiveStart string
	var bodyName string
	var bodyResourceTags string
	var bodyRuleVersion string
	var bodyRules string
	var bodySplitChargeRules string

	cmd := &cobra.Command{
		Use:         "x-amz-target-awsinsights-index-service-create-cost-category-definition",
		Short:       "Creates a new Cost Category with the requested name and rules.",
		Long:        "Shortcut for 'x-amz-target-awsinsights-index-service-create-cost-category-definition create-cost-category-definition'. Creates a new Cost Category with the requested name and rules.",
		Example:     "  aws-pp-pp-cli x-amz-target-awsinsights-index-service-create-cost-category-definition --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-awsinsights-index-service-create-cost-category-definition.create-cost-category-definition", "pp:method": "POST", "pp:path": "http://ce.us-east-1.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.CreateCostCategoryDefinition"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("name") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "name")
			}
			if !cmd.Flags().Changed("rule-version") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "rule-version")
			}
			if !cmd.Flags().Changed("rules") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "rules")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://ce.us-east-1.amazonaws.com/#X-Amz-Target=AWSInsightsIndexService.CreateCostCategoryDefinition"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyDefaultValue != "" {
				body["DefaultValue"] = bodyDefaultValue
			}
			if bodyEffectiveStart != "" {
				body["EffectiveStart"] = bodyEffectiveStart
			}
			if bodyName != "" {
				body["Name"] = bodyName
			}
			if bodyResourceTags != "" {
				var parsedResourceTags any
				if err := json.Unmarshal([]byte(bodyResourceTags), &parsedResourceTags); err != nil {
					return fmt.Errorf("parsing --resource-tags JSON: %w", err)
				}
				body["ResourceTags"] = parsedResourceTags
			}
			if bodyRuleVersion != "" {
				body["RuleVersion"] = bodyRuleVersion
			}
			if bodyRules != "" {
				var parsedRules any
				if err := json.Unmarshal([]byte(bodyRules), &parsedRules); err != nil {
					return fmt.Errorf("parsing --rules JSON: %w", err)
				}
				body["Rules"] = parsedRules
			}
			if bodySplitChargeRules != "" {
				var parsedSplitChargeRules any
				if err := json.Unmarshal([]byte(bodySplitChargeRules), &parsedSplitChargeRules); err != nil {
					return fmt.Errorf("parsing --split-charge-rules JSON: %w", err)
				}
				body["SplitChargeRules"] = parsedSplitChargeRules
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDefaultValue, "default-value", "", "The default value for the cost category.")
	cmd.Flags().StringVar(&bodyEffectiveStart, "effective-start", "", "The period of time that you want the usage and costs for.")
	cmd.Flags().StringVar(&bodyName, "name", "", "The unique name of the Cost Category.")
	cmd.Flags().StringVar(&bodyResourceTags, "resource-tags", "", "Resource tags")
	cmd.Flags().StringVar(&bodyRuleVersion, "rule-version", "", "The rule schema version in this particular Cost Category.")
	cmd.Flags().StringVar(&bodyRules, "rules", "", "Rules")
	cmd.Flags().StringVar(&bodySplitChargeRules, "split-charge-rules", "", "Split charge rules")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
