// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newProductsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagNextToken string
	var flagMaxResults int
	var flagProductArn string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "products",
		Short:       "<p>Returns information about product integrations in Security Hub.</p> <p>You can optionally provide an integration...",
		Long:        "Shortcut for 'products describe'. <p>Returns information about product integrations in Security Hub.</p> <p>You can optionally provide an integration...",
		Example:     "  aws-pp-pp-cli products",
		Annotations: map[string]string{"pp:endpoint": "products.describe", "pp:method": "GET", "pp:path": "http://securityhub.us-east-1.amazonaws.com/products", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://securityhub.us-east-1.amazonaws.com/products"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "products", path, map[string]string{
				"NextToken":  fmt.Sprintf("%v", flagNextToken),
				"MaxResults": fmt.Sprintf("%v", flagMaxResults),
				"ProductArn": fmt.Sprintf("%v", flagProductArn),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagNextToken, "next-token", "", "<p>The token that is required for pagination. On your first call to the <code>DescribeProducts</code> operation, set...")
	cmd.Flags().IntVar(&flagMaxResults, "max-results", 0, "The maximum number of results to return.")
	cmd.Flags().StringVar(&flagProductArn, "product-arn", "", "The ARN of the integration to return.")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
