// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101StartImportPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyDestinations string
	var bodyEndEventTime string
	var bodyImportId string
	var bodyImportSourceS3S3BucketAccessRoleArn string
	var bodyImportSourceS3S3BucketRegion string
	var bodyImportSourceS3S3LocationUri string
	var bodyStartEventTime string

	cmd := &cobra.Command{
		Use:         "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-start-import",
		Short:       "<p> Starts an import of logged trail events from a source S3 bucket to a destination event data store. By default,...",
		Long:        "Shortcut for 'x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-start-import start-import'. <p> Starts an import of logged trail events from a source S3 bucket to a destination event data store. By default,...",
		Example:     "  aws-pp-pp-cli x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-start-import",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-start-import.start-import", "pp:method": "POST", "pp:path": "http://cloudtrail.us-east-1.amazonaws.com/#X-Amz-Target=com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.StartImport"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("import-source-s3-s3-bucket-access-role-arn") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "import-source-s3-s3-bucket-access-role-arn")
			}
			if !cmd.Flags().Changed("import-source-s3-s3-bucket-region") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "import-source-s3-s3-bucket-region")
			}
			if !cmd.Flags().Changed("import-source-s3-s3-location-uri") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "import-source-s3-s3-location-uri")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://cloudtrail.us-east-1.amazonaws.com/#X-Amz-Target=com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.StartImport"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyDestinations != "" {
				var parsedDestinations any
				if err := json.Unmarshal([]byte(bodyDestinations), &parsedDestinations); err != nil {
					return fmt.Errorf("parsing --destinations JSON: %w", err)
				}
				body["Destinations"] = parsedDestinations
			}
			if bodyEndEventTime != "" {
				body["EndEventTime"] = bodyEndEventTime
			}
			if bodyImportId != "" {
				body["ImportId"] = bodyImportId
			}
			{
				nestedImportSource := map[string]any{}
				{
					nestedImportSourceS3 := map[string]any{}
					if bodyImportSourceS3S3BucketAccessRoleArn != "" {
						nestedImportSourceS3["S3BucketAccessRoleArn"] = bodyImportSourceS3S3BucketAccessRoleArn
					}
					if bodyImportSourceS3S3BucketRegion != "" {
						nestedImportSourceS3["S3BucketRegion"] = bodyImportSourceS3S3BucketRegion
					}
					if bodyImportSourceS3S3LocationUri != "" {
						nestedImportSourceS3["S3LocationUri"] = bodyImportSourceS3S3LocationUri
					}
					if len(nestedImportSourceS3) > 0 {
						nestedImportSource["S3"] = nestedImportSourceS3
					}
				}
				if len(nestedImportSource) > 0 {
					body["ImportSource"] = nestedImportSource
				}
			}
			if bodyStartEventTime != "" {
				body["StartEventTime"] = bodyStartEventTime
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDestinations, "destinations", "", "Destinations")
	cmd.Flags().StringVar(&bodyEndEventTime, "end-event-time", "", "End event time")
	cmd.Flags().StringVar(&bodyImportId, "import-id", "", "Import id")
	cmd.Flags().StringVar(&bodyImportSourceS3S3BucketAccessRoleArn, "import-source-s3-s3-bucket-access-role-arn", "", "S3 bucket access role arn")
	cmd.Flags().StringVar(&bodyImportSourceS3S3BucketRegion, "import-source-s3-s3-bucket-region", "", "S3 bucket region")
	cmd.Flags().StringVar(&bodyImportSourceS3S3LocationUri, "import-source-s3-s3-location-uri", "", "S3 location uri")
	cmd.Flags().StringVar(&bodyStartEventTime, "start-event-time", "", "Start event time")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
