// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101StartQueryPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyDeliveryS3Uri string
	var bodyQueryStatement string

	cmd := &cobra.Command{
		Use:         "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-start-query",
		Short:       "Starts a CloudTrail Lake query. The required <code>QueryStatement</code> parameter provides your SQL query, enclosed...",
		Long:        "Shortcut for 'x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-start-query start-query'. Starts a CloudTrail Lake query. The required <code>QueryStatement</code> parameter provides your SQL query, enclosed...",
		Example:     "  aws-pp-pp-cli x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-start-query --query-statement example-value",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-start-query.start-query", "pp:method": "POST", "pp:path": "http://cloudtrail.us-east-1.amazonaws.com/#X-Amz-Target=com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.StartQuery"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("query-statement") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "query-statement")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://cloudtrail.us-east-1.amazonaws.com/#X-Amz-Target=com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.StartQuery"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyDeliveryS3Uri != "" {
				body["DeliveryS3Uri"] = bodyDeliveryS3Uri
			}
			if bodyQueryStatement != "" {
				body["QueryStatement"] = bodyQueryStatement
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDeliveryS3Uri, "delivery-s3-uri", "", "Delivery s3 uri")
	cmd.Flags().StringVar(&bodyQueryStatement, "query-statement", "", "Query statement")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
