// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetAwshealth20160804DescribeEventAggregatesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagMaxResults string
	var flagNextToken string
	var bodyAggregateField string
	var bodyFilterAvailabilityZones string
	var bodyFilterEndTimes string
	var bodyFilterEntityArns string
	var bodyFilterEntityValues string
	var bodyFilterEventArns string
	var bodyFilterEventStatusCodes string
	var bodyFilterEventTypeCategories string
	var bodyFilterEventTypeCodes string
	var bodyFilterLastUpdatedTimes string
	var bodyFilterRegions string
	var bodyFilterServices string
	var bodyFilterStartTimes string
	var bodyFilterTags string

	cmd := &cobra.Command{
		Use:         "x-amz-target-awshealth-20160804-describe-event-aggregates",
		Short:       "<p>Returns the number of events of each event type (issue, scheduled change, and account notification). If no filter...",
		Long:        "Shortcut for 'x-amz-target-awshealth-20160804-describe-event-aggregates describe-event-aggregates'. <p>Returns the number of events of each event type (issue, scheduled change, and account notification). If no filter...",
		Example:     "  aws-pp-pp-cli x-amz-target-awshealth-20160804-describe-event-aggregates --aggregate-field example-value",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-awshealth-20160804-describe-event-aggregates.describe-event-aggregates", "pp:method": "POST", "pp:path": "https://health.us-east-1.amazonaws.com/#X-Amz-Target=AWSHealth_20160804.DescribeEventAggregates"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("aggregate-field") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "aggregate-field")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://health.us-east-1.amazonaws.com/#X-Amz-Target=AWSHealth_20160804.DescribeEventAggregates"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAggregateField != "" {
				body["aggregateField"] = bodyAggregateField
			}
			{
				nestedFilter := map[string]any{}
				if bodyFilterAvailabilityZones != "" {
					var parsedFilterAvailabilityZones any
					if err := json.Unmarshal([]byte(bodyFilterAvailabilityZones), &parsedFilterAvailabilityZones); err != nil {
						return fmt.Errorf("parsing --filter-availability-zones JSON: %w", err)
					}
					nestedFilter["availabilityZones"] = parsedFilterAvailabilityZones
				}
				if bodyFilterEndTimes != "" {
					var parsedFilterEndTimes any
					if err := json.Unmarshal([]byte(bodyFilterEndTimes), &parsedFilterEndTimes); err != nil {
						return fmt.Errorf("parsing --filter-end-times JSON: %w", err)
					}
					nestedFilter["endTimes"] = parsedFilterEndTimes
				}
				if bodyFilterEntityArns != "" {
					var parsedFilterEntityArns any
					if err := json.Unmarshal([]byte(bodyFilterEntityArns), &parsedFilterEntityArns); err != nil {
						return fmt.Errorf("parsing --filter-entity-arns JSON: %w", err)
					}
					nestedFilter["entityArns"] = parsedFilterEntityArns
				}
				if bodyFilterEntityValues != "" {
					var parsedFilterEntityValues any
					if err := json.Unmarshal([]byte(bodyFilterEntityValues), &parsedFilterEntityValues); err != nil {
						return fmt.Errorf("parsing --filter-entity-values JSON: %w", err)
					}
					nestedFilter["entityValues"] = parsedFilterEntityValues
				}
				if bodyFilterEventArns != "" {
					var parsedFilterEventArns any
					if err := json.Unmarshal([]byte(bodyFilterEventArns), &parsedFilterEventArns); err != nil {
						return fmt.Errorf("parsing --filter-event-arns JSON: %w", err)
					}
					nestedFilter["eventArns"] = parsedFilterEventArns
				}
				if bodyFilterEventStatusCodes != "" {
					var parsedFilterEventStatusCodes any
					if err := json.Unmarshal([]byte(bodyFilterEventStatusCodes), &parsedFilterEventStatusCodes); err != nil {
						return fmt.Errorf("parsing --filter-event-status-codes JSON: %w", err)
					}
					nestedFilter["eventStatusCodes"] = parsedFilterEventStatusCodes
				}
				if bodyFilterEventTypeCategories != "" {
					var parsedFilterEventTypeCategories any
					if err := json.Unmarshal([]byte(bodyFilterEventTypeCategories), &parsedFilterEventTypeCategories); err != nil {
						return fmt.Errorf("parsing --filter-event-type-categories JSON: %w", err)
					}
					nestedFilter["eventTypeCategories"] = parsedFilterEventTypeCategories
				}
				if bodyFilterEventTypeCodes != "" {
					var parsedFilterEventTypeCodes any
					if err := json.Unmarshal([]byte(bodyFilterEventTypeCodes), &parsedFilterEventTypeCodes); err != nil {
						return fmt.Errorf("parsing --filter-event-type-codes JSON: %w", err)
					}
					nestedFilter["eventTypeCodes"] = parsedFilterEventTypeCodes
				}
				if bodyFilterLastUpdatedTimes != "" {
					var parsedFilterLastUpdatedTimes any
					if err := json.Unmarshal([]byte(bodyFilterLastUpdatedTimes), &parsedFilterLastUpdatedTimes); err != nil {
						return fmt.Errorf("parsing --filter-last-updated-times JSON: %w", err)
					}
					nestedFilter["lastUpdatedTimes"] = parsedFilterLastUpdatedTimes
				}
				if bodyFilterRegions != "" {
					var parsedFilterRegions any
					if err := json.Unmarshal([]byte(bodyFilterRegions), &parsedFilterRegions); err != nil {
						return fmt.Errorf("parsing --filter-regions JSON: %w", err)
					}
					nestedFilter["regions"] = parsedFilterRegions
				}
				if bodyFilterServices != "" {
					var parsedFilterServices any
					if err := json.Unmarshal([]byte(bodyFilterServices), &parsedFilterServices); err != nil {
						return fmt.Errorf("parsing --filter-services JSON: %w", err)
					}
					nestedFilter["services"] = parsedFilterServices
				}
				if bodyFilterStartTimes != "" {
					var parsedFilterStartTimes any
					if err := json.Unmarshal([]byte(bodyFilterStartTimes), &parsedFilterStartTimes); err != nil {
						return fmt.Errorf("parsing --filter-start-times JSON: %w", err)
					}
					nestedFilter["startTimes"] = parsedFilterStartTimes
				}
				if bodyFilterTags != "" {
					var parsedFilterTags any
					if err := json.Unmarshal([]byte(bodyFilterTags), &parsedFilterTags); err != nil {
						return fmt.Errorf("parsing --filter-tags JSON: %w", err)
					}
					nestedFilter["tags"] = parsedFilterTags
				}
				if len(nestedFilter) > 0 {
					body["filter"] = nestedFilter
				}
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagMaxResults, "max-results", "", "Pagination limit")
	cmd.Flags().StringVar(&flagNextToken, "next-token", "", "Pagination token")
	cmd.Flags().StringVar(&bodyAggregateField, "aggregate-field", "", "Aggregate field")
	cmd.Flags().StringVar(&bodyFilterAvailabilityZones, "filter-availability-zones", "", "Availability zones")
	cmd.Flags().StringVar(&bodyFilterEndTimes, "filter-end-times", "", "End times")
	cmd.Flags().StringVar(&bodyFilterEntityArns, "filter-entity-arns", "", "Entity arns")
	cmd.Flags().StringVar(&bodyFilterEntityValues, "filter-entity-values", "", "Entity values")
	cmd.Flags().StringVar(&bodyFilterEventArns, "filter-event-arns", "", "Event arns")
	cmd.Flags().StringVar(&bodyFilterEventStatusCodes, "filter-event-status-codes", "", "Event status codes")
	cmd.Flags().StringVar(&bodyFilterEventTypeCategories, "filter-event-type-categories", "", "Event type categories")
	cmd.Flags().StringVar(&bodyFilterEventTypeCodes, "filter-event-type-codes", "", "Event type codes")
	cmd.Flags().StringVar(&bodyFilterLastUpdatedTimes, "filter-last-updated-times", "", "Last updated times")
	cmd.Flags().StringVar(&bodyFilterRegions, "filter-regions", "", "Regions")
	cmd.Flags().StringVar(&bodyFilterServices, "filter-services", "", "Services")
	cmd.Flags().StringVar(&bodyFilterStartTimes, "filter-start-times", "", "Start times")
	cmd.Flags().StringVar(&bodyFilterTags, "filter-tags", "", "Tags")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
