// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetAwshealth20160804DescribeEventsForOrganizationPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagMaxResults string
	var flagNextToken string
	var bodyFilterAwsAccountIds string
	var bodyFilterEndTimeFrom string
	var bodyFilterEndTimeTo string
	var bodyFilterEntityArns string
	var bodyFilterEntityValues string
	var bodyFilterEventStatusCodes string
	var bodyFilterEventTypeCategories string
	var bodyFilterEventTypeCodes string
	var bodyFilterLastUpdatedTimeFrom string
	var bodyFilterLastUpdatedTimeTo string
	var bodyFilterRegions string
	var bodyFilterServices string
	var bodyFilterStartTimeFrom string
	var bodyFilterStartTimeTo string
	var bodyLocale string

	cmd := &cobra.Command{
		Use:         "x-amz-target-awshealth-20160804-describe-events-for-organization",
		Short:       "<p>Returns information about events across your organization in Organizations. You can use the<code>filters</code>...",
		Long:        "Shortcut for 'x-amz-target-awshealth-20160804-describe-events-for-organization describe-events-for-organization'. <p>Returns information about events across your organization in Organizations. You can use the<code>filters</code>...",
		Example:     "  aws-pp-pp-cli x-amz-target-awshealth-20160804-describe-events-for-organization",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-awshealth-20160804-describe-events-for-organization.describe-events-for-organization", "pp:method": "POST", "pp:path": "https://health.us-east-1.amazonaws.com/#X-Amz-Target=AWSHealth_20160804.DescribeEventsForOrganization"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "https://health.us-east-1.amazonaws.com/#X-Amz-Target=AWSHealth_20160804.DescribeEventsForOrganization"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			{
				nestedFilter := map[string]any{}
				if bodyFilterAwsAccountIds != "" {
					var parsedFilterAwsAccountIds any
					if err := json.Unmarshal([]byte(bodyFilterAwsAccountIds), &parsedFilterAwsAccountIds); err != nil {
						return fmt.Errorf("parsing --filter-aws-account-ids JSON: %w", err)
					}
					nestedFilter["awsAccountIds"] = parsedFilterAwsAccountIds
				}
				{
					nestedFilterEndTime := map[string]any{}
					if bodyFilterEndTimeFrom != "" {
						nestedFilterEndTime["from"] = bodyFilterEndTimeFrom
					}
					if bodyFilterEndTimeTo != "" {
						nestedFilterEndTime["to"] = bodyFilterEndTimeTo
					}
					if len(nestedFilterEndTime) > 0 {
						nestedFilter["endTime"] = nestedFilterEndTime
					}
				}
				if bodyFilterEntityArns != "" {
					var parsedFilterEntityArns any
					if err := json.Unmarshal([]byte(bodyFilterEntityArns), &parsedFilterEntityArns); err != nil {
						return fmt.Errorf("parsing --filter-entity-arns JSON: %w", err)
					}
					nestedFilter["entityArns"] = parsedFilterEntityArns
				}
				if bodyFilterEntityValues != "" {
					var parsedFilterEntityValues any
					if err := json.Unmarshal([]byte(bodyFilterEntityValues), &parsedFilterEntityValues); err != nil {
						return fmt.Errorf("parsing --filter-entity-values JSON: %w", err)
					}
					nestedFilter["entityValues"] = parsedFilterEntityValues
				}
				if bodyFilterEventStatusCodes != "" {
					var parsedFilterEventStatusCodes any
					if err := json.Unmarshal([]byte(bodyFilterEventStatusCodes), &parsedFilterEventStatusCodes); err != nil {
						return fmt.Errorf("parsing --filter-event-status-codes JSON: %w", err)
					}
					nestedFilter["eventStatusCodes"] = parsedFilterEventStatusCodes
				}
				if bodyFilterEventTypeCategories != "" {
					var parsedFilterEventTypeCategories any
					if err := json.Unmarshal([]byte(bodyFilterEventTypeCategories), &parsedFilterEventTypeCategories); err != nil {
						return fmt.Errorf("parsing --filter-event-type-categories JSON: %w", err)
					}
					nestedFilter["eventTypeCategories"] = parsedFilterEventTypeCategories
				}
				if bodyFilterEventTypeCodes != "" {
					var parsedFilterEventTypeCodes any
					if err := json.Unmarshal([]byte(bodyFilterEventTypeCodes), &parsedFilterEventTypeCodes); err != nil {
						return fmt.Errorf("parsing --filter-event-type-codes JSON: %w", err)
					}
					nestedFilter["eventTypeCodes"] = parsedFilterEventTypeCodes
				}
				{
					nestedFilterLastUpdatedTime := map[string]any{}
					if bodyFilterLastUpdatedTimeFrom != "" {
						nestedFilterLastUpdatedTime["from"] = bodyFilterLastUpdatedTimeFrom
					}
					if bodyFilterLastUpdatedTimeTo != "" {
						nestedFilterLastUpdatedTime["to"] = bodyFilterLastUpdatedTimeTo
					}
					if len(nestedFilterLastUpdatedTime) > 0 {
						nestedFilter["lastUpdatedTime"] = nestedFilterLastUpdatedTime
					}
				}
				if bodyFilterRegions != "" {
					var parsedFilterRegions any
					if err := json.Unmarshal([]byte(bodyFilterRegions), &parsedFilterRegions); err != nil {
						return fmt.Errorf("parsing --filter-regions JSON: %w", err)
					}
					nestedFilter["regions"] = parsedFilterRegions
				}
				if bodyFilterServices != "" {
					var parsedFilterServices any
					if err := json.Unmarshal([]byte(bodyFilterServices), &parsedFilterServices); err != nil {
						return fmt.Errorf("parsing --filter-services JSON: %w", err)
					}
					nestedFilter["services"] = parsedFilterServices
				}
				{
					nestedFilterStartTime := map[string]any{}
					if bodyFilterStartTimeFrom != "" {
						nestedFilterStartTime["from"] = bodyFilterStartTimeFrom
					}
					if bodyFilterStartTimeTo != "" {
						nestedFilterStartTime["to"] = bodyFilterStartTimeTo
					}
					if len(nestedFilterStartTime) > 0 {
						nestedFilter["startTime"] = nestedFilterStartTime
					}
				}
				if len(nestedFilter) > 0 {
					body["filter"] = nestedFilter
				}
			}
			if bodyLocale != "" {
				body["locale"] = bodyLocale
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagMaxResults, "max-results", "", "Pagination limit")
	cmd.Flags().StringVar(&flagNextToken, "next-token", "", "Pagination token")
	cmd.Flags().StringVar(&bodyFilterAwsAccountIds, "filter-aws-account-ids", "", "Aws account ids")
	cmd.Flags().StringVar(&bodyFilterEndTimeFrom, "filter-end-time-from", "", "From")
	cmd.Flags().StringVar(&bodyFilterEndTimeTo, "filter-end-time-to", "", "To")
	cmd.Flags().StringVar(&bodyFilterEntityArns, "filter-entity-arns", "", "Entity arns")
	cmd.Flags().StringVar(&bodyFilterEntityValues, "filter-entity-values", "", "Entity values")
	cmd.Flags().StringVar(&bodyFilterEventStatusCodes, "filter-event-status-codes", "", "Event status codes")
	cmd.Flags().StringVar(&bodyFilterEventTypeCategories, "filter-event-type-categories", "", "Event type categories")
	cmd.Flags().StringVar(&bodyFilterEventTypeCodes, "filter-event-type-codes", "", "Event type codes")
	cmd.Flags().StringVar(&bodyFilterLastUpdatedTimeFrom, "filter-last-updated-time-from", "", "From")
	cmd.Flags().StringVar(&bodyFilterLastUpdatedTimeTo, "filter-last-updated-time-to", "", "To")
	cmd.Flags().StringVar(&bodyFilterRegions, "filter-regions", "", "Regions")
	cmd.Flags().StringVar(&bodyFilterServices, "filter-services", "", "Services")
	cmd.Flags().StringVar(&bodyFilterStartTimeFrom, "filter-start-time-from", "", "From")
	cmd.Flags().StringVar(&bodyFilterStartTimeTo, "filter-start-time-to", "", "To")
	cmd.Flags().StringVar(&bodyLocale, "locale", "", "Locale")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
