// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101CreateChannelPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyDestinations string
	var bodyName string
	var bodySource string
	var bodyTags string

	cmd := &cobra.Command{
		Use:         "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-create-channel",
		Short:       "Creates a channel for CloudTrail to ingest events from a partner or external source. After you create a channel, a...",
		Long:        "Shortcut for 'x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-create-channel create-channel'. Creates a channel for CloudTrail to ingest events from a partner or external source. After you create a channel, a...",
		Example:     "  aws-pp-pp-cli x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-create-channel --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-create-channel.create-channel", "pp:method": "POST", "pp:path": "http://cloudtrail.us-east-1.amazonaws.com/#X-Amz-Target=com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.CreateChannel"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("destinations") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "destinations")
			}
			if !cmd.Flags().Changed("name") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "name")
			}
			if !cmd.Flags().Changed("source") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "source")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://cloudtrail.us-east-1.amazonaws.com/#X-Amz-Target=com.amazonaws.cloudtrail.v20131101.CloudTrail_20131101.CreateChannel"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyDestinations != "" {
				var parsedDestinations any
				if err := json.Unmarshal([]byte(bodyDestinations), &parsedDestinations); err != nil {
					return fmt.Errorf("parsing --destinations JSON: %w", err)
				}
				body["Destinations"] = parsedDestinations
			}
			if bodyName != "" {
				body["Name"] = bodyName
			}
			if bodySource != "" {
				body["Source"] = bodySource
			}
			if bodyTags != "" {
				var parsedTags any
				if err := json.Unmarshal([]byte(bodyTags), &parsedTags); err != nil {
					return fmt.Errorf("parsing --tags JSON: %w", err)
				}
				body["Tags"] = parsedTags
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDestinations, "destinations", "", "Destinations")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name")
	cmd.Flags().StringVar(&bodySource, "source", "", "Source")
	cmd.Flags().StringVar(&bodyTags, "tags", "", "A list of tags.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
