// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newReportDefinitionUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyDestinationS3LocationBucket string
	var bodyDestinationS3LocationPrefix string
	var bodyFormat string
	var bodyReportDescription string
	var bodyReportFrequency string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update <reportId>",
		Short:       "Updates existing report in AWS Application Cost Profiler.",
		Example:     "  aws-pp-pp-cli report-definition update 550e8400-e29b-41d4-a716-446655440000 --format example-value",
		Annotations: map[string]string{"pp:endpoint": "report-definition.update", "pp:method": "PUT", "pp:path": "http://application-cost-profiler.us-east-1.amazonaws.com/reportDefinition/{reportId}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("format") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "format")
				}
				if !cmd.Flags().Changed("report-description") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "report-description")
				}
				if !cmd.Flags().Changed("report-frequency") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "report-frequency")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://application-cost-profiler.us-east-1.amazonaws.com/reportDefinition/{reportId}"
			path = replacePathParam(path, "reportId", args[0])
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				{
					nestedDestinationS3Location := map[string]any{}
					if bodyDestinationS3LocationBucket != "" {
						nestedDestinationS3Location["bucket"] = bodyDestinationS3LocationBucket
					}
					if bodyDestinationS3LocationPrefix != "" {
						nestedDestinationS3Location["prefix"] = bodyDestinationS3LocationPrefix
					}
					if len(nestedDestinationS3Location) > 0 {
						body["destinationS3Location"] = nestedDestinationS3Location
					}
				}
				if bodyFormat != "" {
					body["format"] = bodyFormat
				}
				if bodyReportDescription != "" {
					body["reportDescription"] = bodyReportDescription
				}
				if bodyReportFrequency != "" {
					body["reportFrequency"] = bodyReportFrequency
				}
			}
			data, statusCode, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "report-definition",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDestinationS3LocationBucket, "destination-s3-location-bucket", "", "Bucket")
	cmd.Flags().StringVar(&bodyDestinationS3LocationPrefix, "destination-s3-location-prefix", "", "Prefix")
	cmd.Flags().StringVar(&bodyFormat, "format", "", "Required. The format to use for the generated report.")
	cmd.Flags().StringVar(&bodyReportDescription, "report-description", "", "Required. Description of the report.")
	cmd.Flags().StringVar(&bodyReportFrequency, "report-frequency", "", "Required. The cadence to generate the report.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
