// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRequestedServiceQuotaChangeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "requested-service-quota-change",
		Short:  "Operations on requested service quota changes",
		Hidden: true,
	}

	cmd.AddCommand(newRequestedServiceQuotaChangeGetCmd(flags))
	cmd.AddCommand(newRequestedServiceQuotaChangeListHistoryCmd(flags))
	cmd.AddCommand(newRequestedServiceQuotaChangeListHistoryByQuotaCmd(flags))
	cmd.AddCommand(newRequestedServiceQuotaChangeRequestCmd(flags))
	return cmd
}
