// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSecurityControlsListDefinitionsCmd(flags *rootFlags) *cobra.Command {
	var flagStandardsArn string
	var flagNextToken string
	var flagMaxResults int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list-definitions",
		Aliases:     []string{"list"},
		Short:       "Lists all of the security controls that apply to a specified standard.",
		Example:     "  aws-pp-pp-cli security-controls list-definitions",
		Annotations: map[string]string{"pp:endpoint": "security-controls.list-definitions", "pp:method": "GET", "pp:path": "http://securityhub.us-east-1.amazonaws.com/securityControls/definitions", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "http://securityhub.us-east-1.amazonaws.com/securityControls/definitions"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "security-controls", path, map[string]string{
				"StandardsArn": fmt.Sprintf("%v", flagStandardsArn),
				"NextToken":    fmt.Sprintf("%v", flagNextToken),
				"MaxResults":   fmt.Sprintf("%v", flagMaxResults),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStandardsArn, "standards-arn", "", "The Amazon Resource Name (ARN) of the standard that you want to view controls for.")
	cmd.Flags().StringVar(&flagNextToken, "next-token", "", "Optional pagination parameter.")
	cmd.Flags().IntVar(&flagMaxResults, "max-results", 0, "An optional parameter that limits the total results of the API response to the specified number. If this parameter...")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
