// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStandardsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "standards",
		Short:  "Manage standards",
		Hidden: true,
	}

	cmd.AddCommand(newStandardsBatchDisableCmd(flags))
	cmd.AddCommand(newStandardsBatchEnableCmd(flags))
	cmd.AddCommand(newStandardsDescribeCmd(flags))
	cmd.AddCommand(newStandardsDescribeControlsCmd(flags))
	cmd.AddCommand(newStandardsGetEnabledCmd(flags))
	cmd.AddCommand(newStandardsUpdateControlCmd(flags))
	return cmd
}
