// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTagsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "tags",
		Short:  "Manage tags",
		Hidden: true,
	}

	cmd.AddCommand(newTagsListForResourceCmd(flags))
	cmd.AddCommand(newTagsResourceCmd(flags))
	cmd.AddCommand(newTagsUntagResourceCmd(flags))
	return cmd
}
