// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/spf13/cobra"
)

func newTailCmd(flags *rootFlags) *cobra.Command {
	var resource string
	var interval time.Duration
	var follow bool

	cmd := &cobra.Command{
		Use:         "tail [resource]",
		Short:       "Stream live changes by polling the API at regular intervals",
		Annotations: map[string]string{"mcp:read-only": "true"},
		Long: `Tail streams live data changes by polling the API at configurable intervals.
Events are emitted as NDJSON to stdout for piping to other tools.
Gracefully shuts down on SIGTERM/SIGINT.

Note: For APIs with WebSocket or SSE support, a future version will use
native streaming instead of polling.`,
		Example: `  # Tail all changes every 10 seconds
  aws-pp-pp-cli tail --interval 10s

  # Tail a specific resource
  aws-pp-pp-cli tail messages --interval 5s

  # Pipe to jq for filtering
  aws-pp-pp-cli tail events --interval 30s | jq 'select(.type == "error")'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				resource = args[0]
			}
			// JSON help envelope: when called with no resource AND --json,
			// surface the list of known resources so agents can discover
			// what to pass without parsing a usage error message.
			// Envelope: {resources: [...], note}.
			if resource == "" && flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"resources": tailKnownResources(),
					"note":      "tail requires a resource name; pass one of the listed names",
				}, flags)
			}
			if resource == "" {
				return fmt.Errorf("resource name required (e.g., 'tail messages')")
			}

			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c.NoCache = true

			path := "/" + resource

			sig := make(chan os.Signal, 1)
			signal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)

			ticker := time.NewTicker(interval)
			defer ticker.Stop()

			enc := json.NewEncoder(os.Stdout)

			fmt.Fprintf(os.Stderr, "Tailing %s every %s (Ctrl+C to stop)\n", resource, interval)

			// Initial fetch
			if err := fetchAndEmit(c, path, enc); err != nil {
				fmt.Fprintf(os.Stderr, "warning: initial fetch failed: %v\n", err)
			}

			for {
				select {
				case <-sig:
					fmt.Fprintln(os.Stderr, "\nShutting down gracefully...")
					return nil
				case <-ticker.C:
					if err := fetchAndEmit(c, path, enc); err != nil {
						fmt.Fprintf(os.Stderr, "warning: poll failed: %v\n", err)
					}
				}
			}
		},
	}

	cmd.Flags().StringVar(&resource, "resource", "", "Resource type to tail")
	cmd.Flags().DurationVar(&interval, "interval", 10*time.Second, "Poll interval")
	cmd.Flags().BoolVar(&follow, "follow", true, "Keep running (set --follow=false for single poll)")

	return cmd
}

// tailKnownResources returns the resource names this CLI exposes, so the
// no-arg JSON help envelope can list them without depending on sync's
// defaultSyncResources (which only exists when sync is generated).
func tailKnownResources() []string {
	return []string{
		"x-amz-target-awsinsights-index-service-create-anomaly-monitor",
		"x-amz-target-awsinsights-index-service-create-anomaly-subscription",
		"x-amz-target-awsinsights-index-service-create-cost-category-definition",
		"x-amz-target-awsinsights-index-service-delete-anomaly-monitor",
		"x-amz-target-awsinsights-index-service-delete-anomaly-subscription",
		"x-amz-target-awsinsights-index-service-delete-cost-category-definition",
		"x-amz-target-awsinsights-index-service-describe-cost-category-definition",
		"x-amz-target-awsinsights-index-service-get-anomalies",
		"x-amz-target-awsinsights-index-service-get-anomaly-monitors",
		"x-amz-target-awsinsights-index-service-get-anomaly-subscriptions",
		"x-amz-target-awsinsights-index-service-get-cost-and-usage",
		"x-amz-target-awsinsights-index-service-get-cost-and-usage-with-resources",
		"x-amz-target-awsinsights-index-service-get-cost-categories",
		"x-amz-target-awsinsights-index-service-get-cost-forecast",
		"x-amz-target-awsinsights-index-service-get-dimension-values",
		"x-amz-target-awsinsights-index-service-get-reservation-coverage",
		"x-amz-target-awsinsights-index-service-get-reservation-purchase-recommendation",
		"x-amz-target-awsinsights-index-service-get-reservation-utilization",
		"x-amz-target-awsinsights-index-service-get-rightsizing-recommendation",
		"x-amz-target-awsinsights-index-service-get-savings-plans-coverage",
		"x-amz-target-awsinsights-index-service-get-savings-plans-purchase-recommendation",
		"x-amz-target-awsinsights-index-service-get-savings-plans-utilization",
		"x-amz-target-awsinsights-index-service-get-savings-plans-utilization-details",
		"x-amz-target-awsinsights-index-service-get-tags",
		"x-amz-target-awsinsights-index-service-get-usage-forecast",
		"x-amz-target-awsinsights-index-service-list-cost-allocation-tags",
		"x-amz-target-awsinsights-index-service-list-cost-category-definitions",
		"x-amz-target-awsinsights-index-service-list-savings-plans-purchase-recommendation-generation",
		"x-amz-target-awsinsights-index-service-list-tags-for-resource",
		"x-amz-target-awsinsights-index-service-provide-anomaly-feedback",
		"x-amz-target-awsinsights-index-service-start-savings-plans-purchase-recommendation-generation",
		"x-amz-target-awsinsights-index-service-tag-resource",
		"x-amz-target-awsinsights-index-service-untag-resource",
		"x-amz-target-awsinsights-index-service-update-anomaly-monitor",
		"x-amz-target-awsinsights-index-service-update-anomaly-subscription",
		"x-amz-target-awsinsights-index-service-update-cost-allocation-tags-status",
		"x-amz-target-awsinsights-index-service-update-cost-category-definition",
		"x-amz-target-awssupport-20130415-add-attachments-to-set",
		"x-amz-target-awssupport-20130415-add-communication-to-case",
		"x-amz-target-awssupport-20130415-create-case",
		"x-amz-target-awssupport-20130415-describe-attachment",
		"x-amz-target-awssupport-20130415-describe-cases",
		"x-amz-target-awssupport-20130415-describe-communications",
		"x-amz-target-awssupport-20130415-describe-services",
		"x-amz-target-awssupport-20130415-describe-severity-levels",
		"x-amz-target-awssupport-20130415-describe-trusted-advisor-check-refresh-statuses",
		"x-amz-target-awssupport-20130415-describe-trusted-advisor-check-result",
		"x-amz-target-awssupport-20130415-describe-trusted-advisor-check-summaries",
		"x-amz-target-awssupport-20130415-describe-trusted-advisor-checks",
		"x-amz-target-awssupport-20130415-refresh-trusted-advisor-check",
		"x-amz-target-awssupport-20130415-resolve-case",
		"x-amz-target-service-quotas-v20190624-associate-service-quota-template",
		"x-amz-target-service-quotas-v20190624-delete-service-quota-increase-request-from-template",
		"x-amz-target-service-quotas-v20190624-disassociate-service-quota-template",
		"x-amz-target-service-quotas-v20190624-get-association-for-service-quota-template",
		"x-amz-target-service-quotas-v20190624-get-awsdefault-service-quota",
		"x-amz-target-service-quotas-v20190624-get-requested-service-quota-change",
		"x-amz-target-service-quotas-v20190624-get-service-quota",
		"x-amz-target-service-quotas-v20190624-get-service-quota-increase-request-from-template",
		"x-amz-target-service-quotas-v20190624-list-awsdefault-service-quotas",
		"x-amz-target-service-quotas-v20190624-list-requested-service-quota-change-history",
		"x-amz-target-service-quotas-v20190624-list-requested-service-quota-change-history-by-quota",
		"x-amz-target-service-quotas-v20190624-list-service-quota-increase-requests-in-template",
		"x-amz-target-service-quotas-v20190624-list-service-quotas",
		"x-amz-target-service-quotas-v20190624-list-services",
		"x-amz-target-service-quotas-v20190624-list-tags-for-resource",
		"x-amz-target-service-quotas-v20190624-put-service-quota-increase-request-into-template",
		"x-amz-target-service-quotas-v20190624-request-service-quota-increase",
		"x-amz-target-service-quotas-v20190624-tag-resource",
		"x-amz-target-service-quotas-v20190624-untag-resource",
	}
}

func fetchAndEmit(c interface {
	Get(string, map[string]string) (json.RawMessage, error)
}, path string, enc *json.Encoder) error {
	data, err := c.Get(path, nil)
	if err != nil {
		return err
	}

	var items []json.RawMessage
	if err := json.Unmarshal(data, &items); err != nil {
		event := map[string]any{
			"event":     "data",
			"timestamp": time.Now().UTC().Format(time.RFC3339),
			"data":      json.RawMessage(data),
		}
		return enc.Encode(event)
	}

	for _, item := range items {
		event := map[string]any{
			"event":     "data",
			"timestamp": time.Now().UTC().Format(time.RFC3339),
			"data":      item,
		}
		if err := enc.Encode(event); err != nil {
			return err
		}
	}
	return nil
}
