// Copyright 2026 zaydiscold. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package store

import (
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	_ "modernc.org/sqlite"
)

// TestStoreWrite_NoSQLITE_BUSY_HighConcurrency exercises the writeMu serialization
// guarantee: 16 fetcher-style goroutines hammer the store with a mix of
// UpsertBatch, SaveSyncState, and SaveSyncCursor calls. Before the mutex
// fix, this test reproduces SQLITE_BUSY at default sync concurrency on
// pure-Go SQLite (modernc.org/sqlite + WAL) because multiple writers
// race for the WAL lock and busy_timeout retries are not exhaustive.
//
// Run under `go test -race` to catch any data races on Store fields.
func TestStoreWrite_NoSQLITE_BUSY_HighConcurrency(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	const goroutines = 16
	const itemsPerBatch = 5

	var wg sync.WaitGroup
	errCh := make(chan error, goroutines*3)

	for g := 0; g < goroutines; g++ {
		wg.Add(1)
		go func(gid int) {
			defer wg.Done()
			rt := fmt.Sprintf("rt_%d", gid)
			items := make([]json.RawMessage, 0, itemsPerBatch)
			for i := 0; i < itemsPerBatch; i++ {
				items = append(items, json.RawMessage(fmt.Sprintf(`{"id": "g%d-i%d"}`, gid, i)))
			}
			if _, _, err := s.UpsertBatch(rt, items); err != nil {
				errCh <- fmt.Errorf("UpsertBatch goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncState(rt, fmt.Sprintf("cursor-%d", gid), itemsPerBatch); err != nil {
				errCh <- fmt.Errorf("SaveSyncState goroutine %d: %w", gid, err)
				return
			}
			if err := s.SaveSyncCursor(rt, fmt.Sprintf("cursor2-%d", gid)); err != nil {
				errCh <- fmt.Errorf("SaveSyncCursor goroutine %d: %w", gid, err)
				return
			}
		}(g)
	}
	wg.Wait()
	close(errCh)

	for err := range errCh {
		if err == nil {
			continue
		}
		// SQLITE_BUSY surfaces as "database is locked" or "SQLITE_BUSY"
		// in the error message — assert neither occurs.
		msg := err.Error()
		if strings.Contains(msg, "SQLITE_BUSY") || strings.Contains(strings.ToLower(msg), "database is locked") {
			t.Fatalf("got SQLITE_BUSY-class error under concurrent writers: %v", err)
		}
		t.Fatalf("unexpected error under concurrent writers: %v", err)
	}

	// Verify all rows persisted: goroutines * itemsPerBatch in the generic
	// resources table.
	db := s.DB()
	var total int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources`).Scan(&total); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if total != goroutines*itemsPerBatch {
		t.Fatalf("resources total = %d, want %d", total, goroutines*itemsPerBatch)
	}
}

// TestStoreWrite_PanicReleasesLock confirms that a panic inside a locked
// section unwinds via defer s.writeMu.Unlock() so subsequent writers can
// proceed. A leaked lock would deadlock the second call indefinitely.
func TestStoreWrite_PanicReleasesLock(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Trigger panic by passing a nil *Store method receiver indirectly:
	// we call UpsertBatch with malformed JSON that survives Unmarshal
	// (it's wrapped in skipped-count handling) — there's no easy panic
	// path inside a locked section that doesn't also corrupt state, so
	// we instead simulate the post-panic state by manually locking and
	// unlocking, then assert subsequent calls succeed.
	func() {
		defer func() {
			recover()
		}()
		s.writeMu.Lock()
		defer s.writeMu.Unlock()
		panic("simulated writer panic")
	}()

	// Subsequent writer must not block.
	done := make(chan struct{})
	go func() {
		if _, _, err := s.UpsertBatch("post_panic", []json.RawMessage{json.RawMessage(`{"id": "x"}`)}); err != nil {
			t.Errorf("post-panic UpsertBatch: %v", err)
		}
		close(done)
	}()
	<-done
}

// TestUpsertBatch_TemplatedIDFieldOverrideWins exercises the
// per-resource ID-field override. When the spec author annotates a
// path-item with x-resource-id, the profiler emits SyncableResource.IDField,
// the generator templates this into resourceIDFieldOverrides, and
// UpsertBatch consults that map first. This test seeds the override map
// at runtime (since the generated table here may or may not declare any
// override) to assert the lookup path itself works.
func TestUpsertBatch_TemplatedIDFieldOverrideWins(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	// Inject a runtime override for a synthetic resource. Item carries
	// no generic-fallback field (no id/name/uuid/...) — only a custom
	// "ticker" field. Without the override, all 3 items would be
	// dropped as PK-unresolved; with it, all 3 land.
	prev, hadPrev := resourceIDFieldOverrides["overrideTest"]
	resourceIDFieldOverrides["overrideTest"] = "ticker"
	defer func() {
		if hadPrev {
			resourceIDFieldOverrides["overrideTest"] = prev
		} else {
			delete(resourceIDFieldOverrides, "overrideTest")
		}
	}()

	items := []json.RawMessage{
		json.RawMessage(`{"ticker": "AAPL", "price": 100}`),
		json.RawMessage(`{"ticker": "GOOG", "price": 200}`),
		json.RawMessage(`{"ticker": "MSFT", "price": 300}`),
	}
	stored, extractFailures, err := s.UpsertBatch("overrideTest", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 3 {
		t.Fatalf("stored = %d, want 3 (templated override should resolve all PKs)", stored)
	}
	if extractFailures != 0 {
		t.Fatalf("extractFailures = %d, want 0", extractFailures)
	}
}

// TestUpsertBatch_GenericFallbackList covers each name in the reduced
// fallback list. The kalshi-accreted names (ticker/event_ticker/series_ticker)
// were dropped because the user owns kalshi and will regenerate
// it with x-resource-id annotations; this test pins what the generic list
// is now responsible for so a future trim doesn't silently break unannotated
// specs.
func TestUpsertBatch_GenericFallbackList(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	for _, key := range []string{"id", "ID", "name", "uuid", "slug", "key", "code", "uid"} {
		t.Run(key, func(t *testing.T) {
			rt := "fallback_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-1")),
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "value-2")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 2 {
				t.Fatalf("stored = %d, want 2 (fallback %q must resolve)", stored, key)
			}
			if extractFailures != 0 {
				t.Fatalf("extractFailures = %d, want 0", extractFailures)
			}
		})
	}

	// Negative: API-specific names dropped must NOT resolve.
	// Spec authors annotate these via x-resource-id instead.
	for _, key := range []string{"ticker", "event_ticker", "series_ticker"} {
		t.Run("dropped_"+key, func(t *testing.T) {
			rt := "dropped_" + key
			items := []json.RawMessage{
				json.RawMessage(fmt.Sprintf(`{%q: %q}`, key, "v1")),
			}
			stored, extractFailures, err := s.UpsertBatch(rt, items)
			if err != nil {
				t.Fatalf("UpsertBatch(%q): %v", key, err)
			}
			if stored != 0 {
				t.Fatalf("stored = %d, want 0 (%q must NOT be in the generic fallback list)", stored, key)
			}
			if extractFailures != 1 {
				t.Fatalf("extractFailures = %d, want 1 (%q drop must surface as extract failure)", extractFailures, key)
			}
		})
	}
}

// TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses pins the third
// return value: items that survive JSON unmarshal but have no extractable
// PK (templated override AND generic fallback both miss) bump
// extractFailures. The sync.go.tmpl call site uses this to emit the
// per-resource primary_key_unresolved sync_anomaly the first time silent
// drops occur.
func TestUpsertBatch_ExtractFailuresReturnedForPerItemMisses(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "ok-1"}`),
		json.RawMessage(`{"some_random_field": "no-pk-here"}`),
		json.RawMessage(`{"id": "ok-2"}`),
		json.RawMessage(`{"another_field": 42}`),
	}
	stored, extractFailures, err := s.UpsertBatch("mixed_extraction", items)
	if err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}
	if stored != 2 {
		t.Fatalf("stored = %d, want 2 (only items with id should land)", stored)
	}
	if extractFailures != 2 {
		t.Fatalf("extractFailures = %d, want 2 (two items have no extractable PK)", extractFailures)
	}
}

// TestUpsertBatch_PopulatesAccountsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed accounts table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAccountsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("accounts", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "accounts").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "accounts")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count accounts: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("accounts count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesActionTargetsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed action_targets table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesActionTargetsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("action-targets", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "action-targets").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "action_targets")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count action_targets: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("action_targets count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesAssociationsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed associations table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesAssociationsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("associations", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "associations").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "associations")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count associations: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("associations count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesFindingAggregatorTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed finding_aggregator table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesFindingAggregatorTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("finding-aggregator", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "finding-aggregator").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "finding_aggregator")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count finding_aggregator: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("finding_aggregator count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesFindingsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed findings table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesFindingsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("findings", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "findings").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "findings")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count findings: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("findings count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesInsightsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed insights table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesInsightsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("insights", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "insights").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "insights")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count insights: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("insights count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesInvitationsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed invitations table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesInvitationsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("invitations", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "invitations").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "invitations")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count invitations: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("invitations count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesMasterTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed master table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesMasterTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("master", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "master").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "master")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count master: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("master count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesMembersTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed members table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesMembersTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("members", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "members").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "members")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count members: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("members count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesOrganizationTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed organization table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesOrganizationTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("organization", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "organization").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "organization")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count organization: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("organization count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesProductSubscriptionsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed product_subscriptions table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesProductSubscriptionsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("product-subscriptions", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "product-subscriptions").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "product_subscriptions")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count product_subscriptions: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("product_subscriptions count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesReportDefinitionTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed report_definition table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesReportDefinitionTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("report-definition", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "report-definition").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "report_definition")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count report_definition: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("report_definition count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesSecurityControlsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed security_controls table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesSecurityControlsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("security-controls", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "security-controls").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "security_controls")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count security_controls: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("security_controls count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesStandardsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed standards table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesStandardsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("standards", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "standards").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "standards")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count standards: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("standards count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesTagsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed tags table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesTagsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("tags", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "tags").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "tags")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count tags: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("tags count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceGetCostCategoriesTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_awsinsights_index_service_get_cost_categories table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceGetCostCategoriesTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-awsinsights-index-service-get-cost-categories", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-awsinsights-index-service-get-cost-categories").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_awsinsights_index_service_get_cost_categories")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_awsinsights_index_service_get_cost_categories: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_awsinsights_index_service_get_cost_categories count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceGetReservationPurchaseRecommendationTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_awsinsights_index_service_get_reservation_purchase_recommendation table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceGetReservationPurchaseRecommendationTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-awsinsights-index-service-get-reservation-purchase-recommendation", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-awsinsights-index-service-get-reservation-purchase-recommendation").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_awsinsights_index_service_get_reservation_purchase_recommendation")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_awsinsights_index_service_get_reservation_purchase_recommendation: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_awsinsights_index_service_get_reservation_purchase_recommendation count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceGetRightsizingRecommendationTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_awsinsights_index_service_get_rightsizing_recommendation table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceGetRightsizingRecommendationTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-awsinsights-index-service-get-rightsizing-recommendation", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-awsinsights-index-service-get-rightsizing-recommendation").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_awsinsights_index_service_get_rightsizing_recommendation")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_awsinsights_index_service_get_rightsizing_recommendation: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_awsinsights_index_service_get_rightsizing_recommendation count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceGetSavingsPlansPurchaseRecommendationTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_awsinsights_index_service_get_savings_plans_purchase_recommendation table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceGetSavingsPlansPurchaseRecommendationTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-awsinsights-index-service-get-savings-plans-purchase-recommendation", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-awsinsights-index-service-get-savings-plans-purchase-recommendation").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_awsinsights_index_service_get_savings_plans_purchase_recommendation")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_awsinsights_index_service_get_savings_plans_purchase_recommendation: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_awsinsights_index_service_get_savings_plans_purchase_recommendation count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceGetTagsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_awsinsights_index_service_get_tags table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceGetTagsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-awsinsights-index-service-get-tags", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-awsinsights-index-service-get-tags").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_awsinsights_index_service_get_tags")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_awsinsights_index_service_get_tags: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_awsinsights_index_service_get_tags count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceListTagsForResourceTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_awsinsights_index_service_list_tags_for_resource table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetAwsinsightsIndexServiceListTagsForResourceTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-awsinsights-index-service-list-tags-for-resource", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-awsinsights-index-service-list-tags-for-resource").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_awsinsights_index_service_list_tags_for_resource")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_awsinsights_index_service_list_tags_for_resource: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_awsinsights_index_service_list_tags_for_resource count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101CreateChannelTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_channel table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101CreateChannelTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-create-channel", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-create-channel").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_channel")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_channel: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_channel count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101CreateEventDataStoreTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_event_data_store table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101CreateEventDataStoreTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-create-event-data-store", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-create-event-data-store").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_event_data_store")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_event_data_store: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_event_data_store count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101CreateTrailTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_trail table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101CreateTrailTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-create-trail", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-create-trail").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_trail")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_trail: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_create_trail count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101DescribeQueryTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_describe_query table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101DescribeQueryTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-describe-query", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-describe-query").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_describe_query")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_describe_query: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_describe_query count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101GetChannelTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_channel table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101GetChannelTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-get-channel", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-get-channel").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_channel")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_channel: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_channel count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101GetEventDataStoreTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_event_data_store table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101GetEventDataStoreTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-get-event-data-store", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-get-event-data-store").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_event_data_store")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_event_data_store: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_event_data_store count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101GetImportTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_import table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101GetImportTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-get-import", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-get-import").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_import")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_import: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_import count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101GetQueryResultsTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_query_results table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101GetQueryResultsTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-get-query-results", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-get-query-results").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_query_results")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_query_results: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_query_results count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101GetTrailStatusTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_trail_status table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101GetTrailStatusTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-get-trail-status", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-get-trail-status").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_trail_status")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_trail_status: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_get_trail_status count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101RestoreEventDataStoreTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_restore_event_data_store table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101RestoreEventDataStoreTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-restore-event-data-store", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-restore-event-data-store").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_restore_event_data_store")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_restore_event_data_store: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_restore_event_data_store count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101StartImportTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_start_import table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101StartImportTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-start-import", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-start-import").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_start_import")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_start_import: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_start_import count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101StopImportTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_stop_import table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101StopImportTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-stop-import", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-stop-import").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_stop_import")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_stop_import: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_stop_import count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101UpdateChannelTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_channel table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101UpdateChannelTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-update-channel", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-update-channel").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_channel")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_channel: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_channel count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101UpdateEventDataStoreTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_event_data_store table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101UpdateEventDataStoreTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-update-event-data-store", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-update-event-data-store").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_event_data_store")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_event_data_store: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_event_data_store count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101UpdateTrailTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_trail table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComAmazonawsCloudtrailV20131101CloudTrail20131101UpdateTrailTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-update-trail", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-com-amazonaws-cloudtrail-v20131101-cloud-trail-20131101-update-trail").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_trail")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_trail: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_com_amazonaws_cloudtrail_v20131101_cloud_trail_20131101_update_trail count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetComputeOptimizerServiceGetEnrollmentStatusTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_compute_optimizer_service_get_enrollment_status table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetComputeOptimizerServiceGetEnrollmentStatusTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-compute-optimizer-service-get-enrollment-status", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-compute-optimizer-service-get-enrollment-status").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_compute_optimizer_service_get_enrollment_status")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_compute_optimizer_service_get_enrollment_status: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_compute_optimizer_service_get_enrollment_status count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetServiceQuotasV20190624ListTagsForResourceTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_service_quotas_v20190624_list_tags_for_resource table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetServiceQuotasV20190624ListTagsForResourceTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-service-quotas-v20190624-list-tags-for-resource", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-service-quotas-v20190624-list-tags-for-resource").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_service_quotas_v20190624_list_tags_for_resource")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_service_quotas_v20190624_list_tags_for_resource: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_service_quotas_v20190624_list_tags_for_resource count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetStarlingDoveServiceGetResourceEvaluationSummaryTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_starling_dove_service_get_resource_evaluation_summary table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetStarlingDoveServiceGetResourceEvaluationSummaryTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-starling-dove-service-get-resource-evaluation-summary", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-starling-dove-service-get-resource-evaluation-summary").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_starling_dove_service_get_resource_evaluation_summary")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_starling_dove_service_get_resource_evaluation_summary: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_starling_dove_service_get_resource_evaluation_summary count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}

// TestUpsertBatch_PopulatesXAmzTargetStarlingDoveServiceListTagsForResourceTable verifies that UpsertBatch
// dispatches paginated items into both the generic resources table AND the
// typed x_amz_target_starling_dove_service_list_tags_for_resource table. Regression for issue #268: before the fix, paginated
// syncs only filled the generic resources table, so domain commands that
// query the typed table saw zero rows.
func TestUpsertBatch_PopulatesXAmzTargetStarlingDoveServiceListTagsForResourceTable(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "data.db")
	s, err := Open(dbPath)
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	defer s.Close()

	items := []json.RawMessage{
		json.RawMessage(`{"id": "test-001"}`),
		json.RawMessage(`{"id": "test-002"}`),
		json.RawMessage(`{"id": "test-003"}`),
	}
	if _, _, err := s.UpsertBatch("x-amz-target-starling-dove-service-list-tags-for-resource", items); err != nil {
		t.Fatalf("UpsertBatch: %v", err)
	}

	db := s.DB()

	var generic int
	if err := db.QueryRow(`SELECT COUNT(*) FROM resources WHERE resource_type = ?`, "x-amz-target-starling-dove-service-list-tags-for-resource").Scan(&generic); err != nil {
		t.Fatalf("count resources: %v", err)
	}
	if generic != len(items) {
		t.Fatalf("resources count = %d, want %d", generic, len(items))
	}

	var typed int
	typedQuery := fmt.Sprintf(`SELECT COUNT(*) FROM "%s"`, "x_amz_target_starling_dove_service_list_tags_for_resource")
	if err := db.QueryRow(typedQuery).Scan(&typed); err != nil {
		t.Fatalf("count x_amz_target_starling_dove_service_list_tags_for_resource: %v", err)
	}
	if typed != len(items) {
		t.Fatalf("x_amz_target_starling_dove_service_list_tags_for_resource count = %d, want %d (typed table not populated by UpsertBatch)", typed, len(items))
	}
}
